// Generated by OffScroll Typst renderer
// Edition: The Independent — 2026-03-08

#import "templates.typ": *

#set page("us-letter",
  margin: 0.5in,
  footer: context {
    if here().page() > 1 {
      set text(7pt, font: "Source Sans 3", fill: luma(153))
      line(length: 100%, stroke: 0.5pt + luma(204))
      v(0.05in)
      align(center)[The Independent \u{2014} 2026-03-08]
    }
  }
)

#set text(10pt, font: "Source Serif 4", fill: luma(26), hyphenate: true)
#set par(justify: true, leading: 0.52em)

#set-edition-config(scale: "tight", weights: "three", lead-amplifications: ("scale-bump",))

#masthead([The Independent], [Vol. 2, No. 11], [2026-03-08]
)

// --- Front Page Feature ---
#feature-article(
  title: [The Rise of Home Servers],
  kicker: [Cover Story],
  author: [Sarah Chen],
  source-name: [TechIndependent],
  deck: [Local Area Networks are experiencing a renaissance as more people realize the value of owning their own infrastructure.],
  lead-pre: [],
  lead-cap: [R],
  lead-rest: [ather than relying on cloud providers, individuals and small communities are building resilient systems that work offline and maintain control over their data. This movement represents a fundamental shift in how we think about computing: from renting from corporations to owning our digital lives.],
  body-paragraphs: (),
  edited-for-length: false,
)


#section-label([Front Page])
#standard-article(
  title: [Why Raspberry Pi 5 Changed Everything],
  author: [Marcus Webb],
  source-name: [HardwareToday],
  images: (),
  paragraphs: (
  [Raspberry Pi 5 has become the go-to platform for self-hosting projects. With improved performance and lower power consumption, it makes running a personal cloud server feasible even in rural areas with limited electricity. The ecosystem of free and open-source software has matured significantly, making setup accessible to non-technical users.],
),
  insert-map: (:),
  word-count: 65,
  edited-for-length: false,
  debug-mode: false,
  is-lead: true,
  deck: [Raspberry Pi 5 has become the go-to platform for self-hosting projects.],
)


#article-row((
  [
    #section-label([Technology & Society])
    #standard-article(
  title: [Why Email Will Never Die],
  author: [Dr. James Wilson],
  source-name: [],
  images: (),
  paragraphs: (
  [Email remains the most resilient communication protocol on the internet. Unlike social media platforms that can disappear overnight, email has survived for decades because it is decentralized and standards-based. Experts predict email will outlast every current social platform by decades.],
),
  insert-map: (:),
  word-count: 48,
  edited-for-length: false,
  debug-mode: false,
  is-lead: true,
  deck: [Email remains the most resilient communication protocol on the internet.],
)

  ],
  [
    #thread-article(
  headline: [The Cost of Convenience: A Reckoning],
  author: [\@alex\@techdebate.net],
  source-name: [],
  editorial-note: [A multi-part discussion on the hidden costs of outsourcing our digital lives to platforms we don't control.],
  posts: (
  [Thread: For the last 20 years we've been told that the cloud is more secure, more reliable, and more efficient than anything we could build ourselves. But what we've actually outsourced is control over our own data and our ability to communicate without intermediaries.],
  [Every time we use a centralized platform, we're voting with our data. We're telling corporations that it's okay to collect, analyze, and monetize our personal information. The cost of convenience has been our privacy and autonomy.],
  [The good news? We're starting to see a real alternative emerge. Open protocols, federated systems, and local-first software are becoming practical and user-friendly. The path back to digital autonomy is becoming clearer.],
),
)

  ],
), ruled-indices: (1,))

#standard-article(
  title: [],
  author: [\@fedidev\@fosstodon.org],
  source-name: [],
  images: (),
  paragraphs: (
  [The ActivityPub protocol has gained traction beyond Mastodon, with implementations now available for blogs, photo galleries, and video platforms.],
),
  insert-map: (:),
  word-count: 21,
  edited-for-length: false,
  debug-mode: false,
)


#article-row((
  [
    #section-label([Perspectives])
    #standard-article(
  title: [Building Our Own Digital Future],
  author: [Elena Rodriguez],
  source-name: [],
  images: (),
  paragraphs: (
  [Digital sovereignty isn't just a technical problem—it's a philosophical one. It's about asking fundamental questions: Who owns my data? Who decides what I can see? Who profits from my attention? These are no longer abstract concerns; they are urgent practical questions that affect billions of people daily. The movement toward decentralized systems isn't driven by technologists alone; it's driven by ordinary people who are tired of surrendering control. From small towns building community networks to individuals running home servers in closets, the infrastructure of digital freedom is being built brick by brick.],
),
  insert-map: (:),
  word-count: 124,
  edited-for-length: false,
  debug-mode: false,
  is-lead: true,
  deck: [Digital sovereignty isn't just a technical problem—it's a philosophical one.],
)

  ],
  [
    #standard-article(
  title: [The Developer Uprising],
  author: [Dev Team at LibreProject],
  source-name: [],
  images: (),
  paragraphs: (
  [Open source development has democratized the tools of the digital age. Anyone with a computer and internet connection can now build and deploy software that rivals commercial offerings. This shift has profound implications for who gets to shape technology and whose interests it serves.],
),
  insert-map: (:),
  word-count: 45,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#standard-article(
  title: [],
  author: [\@cryptocomm\@example.org],
  source-name: [],
  images: (),
  paragraphs: (
  [Matrix protocol adoption continues to grow among organizations that value encrypted, decentralized communication.],
),
  insert-map: (:),
  word-count: 18,
  edited-for-length: false,
  debug-mode: false,
)


#colophon([The Independent], [Vol. 2, No. 11], [2026-03-08])
