// Generated by OffScroll Typst renderer
// Edition: The Critical Dispatch — 2026-03-30

#import "templates.typ": *

#set page("us-letter",
  margin: 0.5in,
  footer: context {
    if here().page() > 1 {
      set text(7pt, font: "Source Sans 3", fill: luma(153))
      line(length: 100%, stroke: 0.5pt + luma(204))
      v(0.05in)
      align(center)[The Critical Dispatch \u{2014} 2026-03-30]
    }
  }
)

#set text(10pt, font: "Source Serif 4", fill: luma(26), hyphenate: true)
#set par(justify: true, leading: 0.52em)

#masthead([The Critical Dispatch], [Vol. 1, No. 052], [2026-03-30]
)

#section-label([Front Page])
#standard-article(
  title: [dbVar August 2020 Release],
  author: [PubMed Health],
  source-name: [PubMed Health],
  images: (),
  paragraphs: (
  [​ d bVar August 2020 Release],
  [Summary:],
  [August dbVar data release New/updated studies: 2
New Variant regions: 63836
New Variant calls: 66248
Non-Redundant Deletions: 2,535,364
Non-Redundant Duplications: 428,062
Non-Redundant Insertions: 1,310,643],
  [dbVar Resources:],
  [Study Browser 
 Human Data Hub 
 Organism List 
 FTP files 
 Tools for analyzing dbVar data 
 Non-Redundant Structural Variants],
  [New/updated studies:],
  [Study: nstd102 (Clinical Structural Variants) 
Publication: See individual variant records for publications
Description: Structural Variants with clinical assertions, submitted to ClinVar by external labs. dbVar now
 imports all placements from ClinVar as "submitted" and only remaps what is missing in order to
 place all variants on both GRCh37 and GRCh38. See Variant Summary counts for nstd102 in \[dbVar
 Variant Summary|/dbvar/content/var\_summary/\#nstd102\]. See the latest statistics for nstd102 in
 \[Summary of nstd102 (Clinical Structural Variants)|/dbvar/content/clinvar\_summary\].
Organism: Human(9606)
Study Type: Case-Set
Submitter: ClinVar (NCBI)
Variant Calls: 65134 
Variant Regions: 62722 
FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
  [Study: nstd194 (Lee et al 2020)],
  [Description: To systematically identify non-reference insertion structural variants among human populations, we],
  [developed an insertion detection pipeline, InserTag, which generates unmapped contigs by local],
  [de-novo assembly and then infers the full-sequence of insertion variants by tracing the contigs],
  [from non-human primates and other human assemblies. By application of the pipeline to 1000 Genomes],
  [Project database, we could identify 1,696 non-reference insertion variants in 2,535 individuals and],
  [re-classify the variants as retention of ancestral sequences or novel sequence insertions based on],
  [the ancestral state. Here, we report 1114 variants which are larger than 100 bp and have genotypes.],
  [See Variant Summary counts for nstd194 in \[dbVar Variant],
  [Summary|/dbvar/content/var\_summary/\#nstd194\].],
  [Organism: Human(9606)],
  [Study Type: Collection],
  [Submitter: Jin-young Lee (Yonsei University)],
  [Variant Calls: 1114],
  [Variant Regions: 1114],
  [FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
),
  insert-map: (:),
  word-count: 273,
  edited-for-length: false,
  debug-mode: false,
)

#pull-quote([See the latest statistics for nstd102 in  \[Summary of nstd102 (Clinical Structural Variants)|/dbvar/content/clinvar\_summary\].], [PubMed Health])


#section-label([Features])
#standard-article(
  title: [Build 136: FTP update for build specific SQL files for non-human organisms],
  author: [PubMed Health],
  source-name: [PubMed Health],
  images: (),
  paragraphs: (
  [The SQL files below have been updated on dbSNP FTP site for the following organisms.],
  [Arabidopsis (taxid 3702)],
  [Chimpanzee (taxid 9598)],
  [Macaque(taxid 9544)],
  [Nematode (taxid 6239)],
  [Pig (taxid 9823)],
  [Rat (taxid 10116)],
  [Orangutan (taxid 9601)],
  [Zebrafish (taxid 7955)],
  [The build specific files (b136\_\*) were missing from the regular build dumps and have been restored for each organism.],
  [Base FTP URL - ftp:\/\/ftp.ncbi.nih.gov/snp/organisms/],
  [./arabidopsis\_3702/database/organism\_data],
  [./arabidopsis\_3702/database/organism\_data/b136\_ContigInfo\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_ContigInfo\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_MapLink\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_MapLink\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz],
  [./arabidopsis\_3702/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz.md5],
  [./arabidopsis\_3702/database/organism\_schema],
  [./arabidopsis\_3702/database/organism\_schema/arabidopsis\_3702\_constraint.sql.gz],
  [./arabidopsis\_3702/database/organism\_schema/arabidopsis\_3702\_index.sql.gz],
  [./arabidopsis\_3702/database/organism\_schema/arabidopsis\_3702\_table.sql.gz],
  [./chimpanzee\_9598/database/organism\_schema],
  [./chimpanzee\_9598/database/organism\_schema/chimpanzee\_9598\_constraint.sql.gz],
  [./chimpanzee\_9598/database/organism\_schema/chimpanzee\_9598\_index.sql.gz],
  [./chimpanzee\_9598/database/organism\_schema/chimpanzee\_9598\_table.sql.gz],
  [./macaque\_9544/database/organism\_data],
  [./macaque\_9544/database/organism\_data/b136\_ContigInfo\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_ContigInfo\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_MapLink\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_MapLink\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz],
  [./macaque\_9544/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz.md5],
  [./macaque\_9544/database/organism\_schema],
  [./macaque\_9544/database/organism\_schema/macaque\_9544\_constraint.sql.gz],
  [./macaque\_9544/database/organism\_schema/macaque\_9544\_index.sql.gz],
  [./macaque\_9544/database/organism\_schema/macaque\_9544\_table.sql.gz],
  [./nematode\_6239/database/organism\_data],
  [./nematode\_6239/database/organism\_data/b136\_ContigInfo\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_ContigInfo\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_MapLink\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_MapLink\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz],
  [./nematode\_6239/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz.md5],
  [./nematode\_6239/database/organism\_schema],
  [./nematode\_6239/database/organism\_schema/nematode\_6239\_constraint.sql.gz],
  [./nematode\_6239/database/organism\_schema/nematode\_6239\_index.sql.gz],
  [./nematode\_6239/database/organism\_schema/nematode\_6239\_table.sql.gz],
  [./pig\_9823/database/organism\_data],
  [./pig\_9823/database/organism\_data/b136\_ContigInfo\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_ContigInfo\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_MapLinkInfo\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_MapLinkInfo\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_MapLink\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_MapLink\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPChrPosOnRef\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPChrPosOnRef\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPContigLoc\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPContigLoc\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPContigLocusId\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPContigLocusId\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPContigProtein\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPContigProtein\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPMapInfo\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPMapInfo\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_data/b136\_SNPMapLinkProtein\_103.bcp.gz],
  [./pig\_9823/database/organism\_data/b136\_SNPMapLinkProtein\_103.bcp.gz.md5],
  [./pig\_9823/database/organism\_schema],
  [./pig\_9823/database/organism\_schema/pig\_9823\_constraint.sql.gz],
  [./pig\_9823/database/organism\_schema/pig\_9823\_index.sql.gz],
  [./pig\_9823/database/organism\_schema/pig\_9823\_table.sql.gz],
  [./rat\_10116/database/organism\_data],
  [./rat\_10116/database/organism\_data/b136\_ContigInfo\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_ContigInfo\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_MapLinkInfo\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_MapLink\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_MapLink\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_Remapped\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_Remapped\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPChrPosOnRef\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPContigLoc\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPContigLocusId\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPContigProtein\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPMapInfo\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz],
  [./rat\_10116/database/organism\_data/b136\_SNPMapLinkProtein\_101.bcp.gz.md5],
  [./rat\_10116/database/organism\_schema],
  [./rat\_10116/database/organism\_schema/rat\_10116\_constraint.sql.gz],
  [./rat\_10116/database/organism\_schema/rat\_10116\_index.sql.gz],
  [./rat\_10116/database/organism\_schema/rat\_10116\_table.sql.gz],
  [./zebrafish\_7955/database/organism\_data],
  [./zebrafish\_7955/database/organism\_data/b136\_ContigInfo\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigLocusId\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigProtein\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigProtein\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPMapInfo\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPChrPosOnRef\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigLoc\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigLoc\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPContigLocusId\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_Remapped\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPChrPosOnRef\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_Remapped\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_ContigInfo\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_MapLinkInfo\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_MapLinkInfo\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_MapLink\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_MapLink\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPMapInfo\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPMapLinkProtein\_102.bcp.gz],
  [./zebrafish\_7955/database/organism\_data/b136\_SNPMapLinkProtein\_102.bcp.gz.md5],
  [./zebrafish\_7955/database/organism\_schema],
  [./zebrafish\_7955/database/organism\_schema/zebrafish\_7955\_index.sql.gz],
  [./zebrafish\_7955/database/organism\_schema/zebrafish\_7955\_table.sql.gz],
  [./zebrafish\_7955/database/organism\_schema/zebrafish\_7955\_constraint.sql.gz],
  [./orangutan\_9601/database/organism\_schema],
  [./orangutan\_9601/database/organism\_schema/orangutan\_9601\_constraint.sql.gz],
  [./orangutan\_9601/database/organism\_schema/orangutan\_9601\_index.sql.gz],
  [./orangutan\_9601/database/organism\_schema/orangutan\_9601\_table.sql.gz],
  [./orangutan\_9601/database/organism\_data],
  [./orangutan\_9601/database/organism\_data/b136\_ContigInfo\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_ContigInfo\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_MapLinkInfo\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_MapLinkInfo\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_MapLink\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_MapLink\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPChrPosOnRef\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPChrPosOnRef\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigLoc\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigLoc\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigLocusId\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigLocusId\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigProtein\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPContigProtein\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPMapInfo\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPMapInfo\_100.bcp.gz.md5],
  [./orangutan\_9601/database/organism\_data/b136\_SNPMapLinkProtein\_100.bcp.gz],
  [./orangutan\_9601/database/organism\_data/b136\_SNPMapLinkProtein\_100.bcp.gz.md5],
),
  insert-map: (:),
  word-count: 1151,
  edited-for-length: false,
  debug-mode: false,
)


#standard-article(
  title: [Apple's Assault on Standards],
  author: [Alex Russell (infrequently noted)],
  source-name: [Alex Russell (infrequently noted)],
  images: (),
  paragraphs: (
  [TL;DR : 
Market competition underlies the enterprise of standards. It creates the only functional test of designs and lets standards-based ecosystems route around single-vendor damage. Without competition, standards bodies have no purpose, and neither they, nor the ecosystems they support, can retain relevance. Apple has poisoned the well through a monopoly on influence, which it has parleyed into suppression of browser choice. This is an existential threat to the web, but also renders web and internet standards moot. Internet standards bodies should recognise the threat and respond.],
  [The Power of Interoperability],
  [Voluntary Adoption Is Foundational to Internet Standards],
  [How Apple Uses Its Monopoly to Centralise and Enclose],
  [Apple's Transgressions Against Voluntary Adoption],
  [Unilateral Off-Ramps],
  [How Apples Crimes Differ From Prior Episodes],
  [Necessary, Proportional Responses],
  [Why Now?],
  [Do Standards Matter?],
  [Internet enthusiasts of the previous century sometimes expressed the power of code by declaring the sovereignty of cyberspace, or that "code is law."],
  [As odd as these claims sound today, they hit a deep truth: end-users, and even governments, lack power to re-litigate choices embodied in software. Software vendors, therefore, have power. Backed by deeply embedded control chokepoints , and without a proportional response from other interests, this control is akin to state power.],
  [Both fear and fervour about these properties developed against a backdrop of libertarian 1 attitudes toward regulation and competition. Attenuating vendor power through interoperability was, among other values, a shared foundation of collaboration for internet pioneers.],
  [The most fervent commitment of this strain was faith in markets to sort out information distribution problems through pricing signals, 2 and that view became embedded deeply into the internet's governance mechanisms. 3 If competition does not function, neither do standards.],
  [The internet's most consequential designs took competitive markets as granted. Many participants believed hardware and software markets would (and should) continue to decouple; that it would be easier for end-users to bring their own software to devices they owned. It is odd from the perspective of 2025 to suggest that swapping browsers, e.g., should come at the cost of replacing hardware. This is why Apple have worked so hard to obscure that this is exactly the situation it has engineered, to the detriment of users, the web, and internet standards.],
  [Internet standards bodies assumed the properties of open operating systems and low-cost software replacement to such an extent that their founding documents scarcely bother to mention them. 4 Only later did statements of shared values see fit to make the subtext clear.],
  [And it has worked. Internet standards have facilitated interoperability that has blunted lock-in, outsized pricing power, and other monopolistic abuses. This role is the entire point of standards at a societal level, and the primary reason that competition law carves out space for competitors to collaborate in developing them. 5],
  [But this is not purely an economic project. Standards attenuate the power of firms that might seek to arrogate code's privileges. Functional interoperability enables competition, reallocating power to users. Standardisation is therefore, at least partially a political project; one that aligns with the values of open societies:],
  [We must ask whether ... we should not prepare for the worst leaders, and hope for the best. But this leads to a new approach to the problem of politics, for it forces us to replace the question: "Who should rule?" by the new question: "How can we so organize political institutions that bad or incompetent rulers can be prevented from doing too much damage?"],
  [— Karl Popper,
"The Open Society and Its Enemies"],
  [Without a counterweight, network effects allow successful tech firms to concentrate wealth and political influence. This power allows them to degrade potential competitive challenges, enabling rent extraction for services that would otherwise be commodities. This mechanism operates through (often legalised) corruption of judicial, regulatory, and electoral systems. When left to fester, it corrodes democracy itself. 6],
  [Apple has deftly used a false cloak of security and privacy to move the internet, and the web in particular, toward enclosure and irrelevance. Cupertino acts as a corrupted, and indeed incompetent, autocrat in our digital lives, even for folks who don't carry iPhones. It accomplishes this trick through abuse of a unique monopoly, allowing it to extract rents, including on the last remnants of open ecosystems it tolerates.],
  [Worse, Apple's centralisation through the App Store entrenches the positions of peer big tech firms, harming the prospects of competitors in turn. Apple have been, over the course of many years, poisonous to internet standards and the moral commitments of that grand project. 7],
  [Despite near continuous horse-race coverage in the tech press, the consequences of this regression in civic/technical affairs is not well socialised.],
  [The Power of Interoperability],
  [Standardisation expands the reach of interoperable technology, pushing firms to innovate, rather than extracting rents on commodities.],
  [Interoperability-in-being gives users choice, forcing competitors to differentiate on quality and not-yet-standard features. Standards expedite interoperability by lowering the costs for implementers and reducing tail risks, e.g. from patent trolls. Over time, a complete enough set of standards can attenuate the power of vendors to extract rents and prevent progress in important domains.],
  [Interoperability is not the only mechanism that can reduce the power of dominant firms, but it is the most powerful. Free and Open Source software ( FOSS ) can provide a counterweight too, but OSS is not a full solution. 8],
  [Voluntary Adoption Is Foundational to Internet Standards],
  [Interoperability, and the economic surpluses that flow from it, are underpinned by voluntary adoption . This is enshrined in the "open stand" principles agreed to by no less than ISOC, IETF , IAB , IEEE, and the W3C . :],
  [...],
  [5. Voluntary Adoption],
  [Standards are voluntarily adopted and success is determined by the market.],
  [— The IAB , IEEE, IETF , ISOC, and W3C ,
"The OpenStand Principles"],
  [This final principle is the shortest, and many readers will understand it as a dodge; a way for Standards Development Organisations ( SDOs ) to avoid being seen to pick winners. But it is more than that.],
  [Voluntary adoption is necessary for internet standards to function, and it creates a presumption of fair play.],
  [Several implications bear mentioning.],
  [First, the principle of voluntary adoption is necessary for effective standards development. Without a mechanism for determining which designs are better, we are unable to make consistent progress. That test never comes from within an SDO ; it is always customer-defined. Writing a standard is not a test of quality, and without a functional market to test designs in, SDOs are irrelevant.],
  [Second, this principle outlines a live-and-let-live doctrine, both within standards bodies and in the market. Participants may want their design to win, but are enjoined from procedural shenanigans to prevent competing designs from also being standardised.],
  [Lastly, voluntary adoption marks customers (developers) and suppliers (browser vendors, etc.) as peers and creates norms of mutual respect within the walls of SDOs .],
  [For all of these reasons, voluntary adoption must be defended, and actions taken to undermine it met with resistance and eventual sanction.],
  [Regulators have had no difficulty in building market tests that demonstrate the power Apple holds in the lives of users.],
  [Some of these tests have produced comical contortions as Apple has attempted to weasel out of its responsibilities. Consider the Trinitarian claim that Safari is simultaneously one product, and also three. Or that iPadOS, despite sharing nearly all code with iOS, marketed under that brand for years, supporting identical features, running the same third-party software, releasing on the same cadence, and running exclusively on the same hardware architecture is (somehow) an entirely different product. 9],
  [But for as clear and effective as regulator's tests have been in piercing these smoke screens, they do not capture the most important aspects of Apple's influence on the market for smartphone software: the monopoly on wealth.],
  [Apple suppresses standards-based platforms and their disruptive potential through a mechanism every software developer understands: wealthy users carry iPhones, and they have all the influence.],
  [Competition law does not explicitly recognise this distortion of the market, but the connection between the influence of the wealthy and the choices available to other end-users is indisputable.],
  [Despite selling fewer than a quarter of smartphones globally for the past decade, Apple has built and anti-competitively maintained a supermonopoly among the wealthiest 10-20% of the world's population who, in turn, control effectively all wealth on the planet. This has handed it control over software distribution due to the social effects of wealth. Apple pairs legitimately superior product attributes (e.g., leading chip design) with anti-user and anticompetitive tactics — e.g., green vs. blue chat bubbles, suppression of browsers — to maintain this position.],
  [Apple has put in place a set of interlocking restrictions to ensure the web cannot disrupt native apps within this user base. Those users, in turn, warp the behaviour of software developers thanks their spending power and positions within the software industry. Developers understand that if they cannot demo their wares to bosses and VCs (all of whom are wealthy) on their own devices, their software might as well not exist.],
  [The long-stable propensity of users who make more than \$100K USD/year to carry iPhones combines with Apple's suppression of browsers and PWA capabilities to ensure developers have no choice but to build native applications. These effects were visible in population-level statistics a decade ago and have been stable ever since:],
  [Knowing whether someone owns an iPad in 2016 allows us to guess correctly whether the person is in the top or bottom income quartile 69 percent of the time. Across all years in our data, no individual brand is as predictive of being high-income as owning an Apple iPhone in 2016.],
  [— Marianne Bertrand and Emir Kamenica,
"Coming Apart? Cultural Distances in the United States Over Time"],
  [Developers are forced into the App Store by missing web capabilities, ensuring an advantage for Apple's proprietary ecosystem. This induces wealthy and influential users to default to the App Store for software, further damping the competitiveness of open platforms.],
  [The monopoly on influence explains why Apple is wedded to legalistic, dissembling tactics in order to prevent the spread of web apps. Should the work of internet and web standards bodies ever become relevant, Cupertino understands the market for software will transform in ways it cannot control or tax.],
  [How Apple Uses Its Monopoly to Centralise and Enclose],
  [Developers are forced into the App Store by a lack of functionality in browsers and web apps. By contrast, Apple has liberally meted out fingerprintable system capabilities to privacy-invading native apps . It has also allowed them to suppress pro-privacy interventions when it serves them. 10],
  [Apple professes that "privacy is a human right" , but this as an attempt to turn the consequences of Apple's own largesse towards data abusers into a marketing asset. Wide-scale privacy erosion has depended, fundamentally, on Apple's own decisions, and it has not recanted.],
  [It was Apple's choice to introduce less safe, less privacy-preserving native apps into iOS. It was also Apple's choice to deny competing browsers engines the freedom of voluntary feature adoption. This has ensured that important underlying capabilities could only ever be accessed through Apple's proprietary APIs, and only ever by those who are willing to agree to Cupertino's extractive terms.],
  [The result has been API enclosure ; appropriation of commodity capabilities that themselves are standards-based — e.g., rich graphics, USB, Bluetooth, NFC, file storage, etc. — by a proprietary ecosystem. Meanwhile, it has delayed and undermined the emergence of safe and privacy-preserving versions of those features on the web.],
  [This, in turn, has created a winner-take-all dynamic inside the app store, harming privacy, security, and competition in the process.],
  [Apple's Transgressions Against Voluntary Adoption],
  [This strategy relies on interlocking policies that harm competitors, and the sabotage of voluntary standards adoption lies at its heart. A Bill of Particulars for crimes against the internet community springs from a small set of undisputed facts.],
  [Apple has:],
  [Restricted competitors from shipping their own implementations of web and internet standards, depriving them access to influential users.],
  [Forced all iOS browsers to use Apple's own defective, impoverished implementation.],
  [Undermined user security and privacy through iOS browser engine monoculture.],
  [Used contractual terms to dissuade competitors from supporting standards Apple disfavours.],
  [Objected spuriously within standards bodies to prevent standardisation of features which Apple offered no counter-proposal. 11],
  [Engaged in marketing and product UI that discourages use of web-based alternatives.],
  [Misled regulators and the public when presented with evidence of the harm from these actions.],
  [Through these and other overt acts, Apple has worked to disempower users, depriving them of choice by preventing open platforms from challenging native apps. 12],
  [This isn't just a fierce market participant competing aggressively. Apple has done violence to the founding ethos of internet and web standards development. Instead of honourably withdrawing from those groups, Apple has maintained a charade of engagement, and gaslights other participants while actively sabotaging the principle of voluntary adoption that internet standards rely on.],
  [Unilateral Off-Ramps],
  [Apple has never been forced to suppress its competitors, nor to create an anticompetitive landscape. Cupertino's senior management have intellectually consistent options that would allow it to pursue growth of the superior (we are told) native app ecosystem without threatening browser choice or the good functioning of internet standards.],
  [Let's consider two: all safe browsers , and no browsers .],
  [Apple could, of course, simply enable the same sort of level playing field for high-quality browsers that every competing general-purpose OS vendor has for the web's entire history. Apple itself facilitates this sort of ecosystem on macOS. 13 Any plausible restrictions stemming from available system resources have long been overcome by progress in mobile hardware, particularly within Apple's ecosystem. 14],
  [The only reasonable restrictions on competing browser engines relate to security. As other vendors have generally had a better track records than Apple regarding sandboxing, incident response, patch gaps, and support for older OS versions, this should be no practical obstacle.],
  [Lest Apple's defenders worry about the impact on Safari, recall that under true browser choice, Apple retains considerable market advantages, including (but not limited to) pre-installation, lower structural costs 15 , and continued differentiation through integration. 16 Such bulwarks have allowed Safari to retain considerable share on macOS in spite of stiff competition and Safari's poor track record on security and standards conformance.],
  [Alternatively, Apple could withdraw Safari while forbidding web content on iOS. This is a fully consistent position, and has been available to Apple from the moment of the App Store's release. The iPod did not include a browser, and many subsequent Apple OSes lack functional browsers. iOS and visionOS are uniquely deficient in this regard. 17],
  [Either way, the decision to undermine choice and standards rests entirely with Apple. It has always had intellectually honest solutions to the problems it has created. Apple cannot claim the situation is anyone else's fault, or that it has had no alternative.],
  [How Apples Crimes Differ From Prior Episodes],
  [Under voluntary implementation, every vendor is free to ship what they please, including Apple. It may be sad, or even damaging, when features go missing from important products, but that is not a calamity; just an input to be priced by the market — a reason for a specific browser to gain or lose share.],
  [It's not enough to cite a lack of features, bungled implementations, peevish behaviour in working groups — or even rank dishonesty — as reason for censure. These are, to greater or lesser degrees, players playing the game. Certain tactics may be distasteful, but are squarely inside the "awful but lawful" zone. Standards venues should allow them, with sanctions for poor behaviour meted out in the social realm.],
  [But by undercutting voluntary implementation, Apple has committed a more fundamental and more dangerous outrage. 18],
  [Some will see a parallel to the Paradox of Tolerance , and I do not believe this is mistaken. Standards bodies can, and should, admit many positions by their participants, but granting membership in good standing to those who are actively poison the basis for standards is madness. It ensures that standards, and the ecosystems that depend on them, wither and die.],
  [By subverting the voluntary nature of open standards, Apple has defanged them as tools for users against the totalising power of technology firms in their digital lives. This high-modernist approach is antithetical to the foundational commitments of internet standards bodies and, over time, erode them.],
  [Indeed, no other vendor has achieved what Apple has in suppressing the web through anticompetitive means. We must not imagine that Apple would stop at the Application layer given a chance. The same mechanism threatens voluntary feature adoption in networking and every other layer down the stack, too.],
  [Necessary, Proportional Responses],
  [The web and internet communities should understand the threat and clock the cumulative harm done to internet standards and open technology ecosystems. It seems to me that this point has hardly been engaged, let alone won, within the walls of SDOs . But if it were, then what? What can be done?],
  [The founding documents of internet SDOs do not include censure mechanisms for sabotage. The W3C 's bylaws, for example, only relate membership in good standing with paying dues. Regardless, it is possible — and I believe urgent — to do more.],
  [First, proposals can be raised to amend bylaws to include mechanisms for censure by votes of the membership for the kinds of outrages alleged here. These are likely to fail, and will surely be rejected at first, but the act of raising these questions has power. Bringing up these issues in plenary meetings can, at a minimum, elicit a response. That, on its own, is valuable to the community.],
  [Next, leadership boards with moral authority can consider the question and issue guidance. The W3C 's Advisory Board and Technical Architecture Group and the IETF 's Internet Architecture Board have the ear of the membership, even on non-technical topics, should they choose to weigh in on the side of their own continued relevance.],
  [Most importantly, individual delegates to Working Groups can recognise that Apple's forced monoculture is illegitimate and corrosive. They can resolve not to accept "Apple does not comment on future products" in response to questions about implementation timelines.],
  [As long as Cupertino demands a monopoly, we must demand it take responsibility for the consequences.],
  [Today, Apple alone chooses which features ship in WebKit, and which can be used by competing browsers. Even if it does not to enable them in Safari, it can provide more to others. It is simply illegitimate for Apple to claim that it cannot, or should not, allow other vendors to reach feature parity between their iOS browsers and other products that use their own engines.],
  [WebKit purports to be Open Source, but in practice Apple has used it to undermine the "bring your own code" foundation of OSS . It is illogical for Apple to cite a disinterest in a feature in Safari as a reason for Apple not to be expected to implement those features in iOS's WebKit binary, making them available for other embedders to flag on.],
  [The sham of WebKit as an Open Source project is incompatible with preventing other vendors from introducing features they would turn on for their iOS users if allowed. The destruction of voluntary adoption is not a shield against critique. Instead, it must heighten expectations. Apple agues it should be singularly entrusted with control over all web features on iOS, despite Safari and WebKit's trailing record on standards' conformance, security, and even privacy. This is nonsense, but so long as it is the law of the land in code, Apple should bear the costs.],
  [Apple alone must be on the hook to implement any and every web platform feature shipped by any and every other engine. It does not need to enable them in Safari, but must make them available for use by others as they see fit.],
  [So long as competing vendors are forced into the App Store and required to use Apple's engine, Cupertino owes much more when it comes to completeness and quality. So long as Cupertino compels use of WebKit, the demand should be echoed back: parity with browser features on other Operating Systems is the minimum bar .],
  [Fundamentally, the web and internet community must stop accepting the premise that Apple should benefit from the protections and privileges of voluntary feature adoption while denying it to others. 19],
  [Lastly, and perhaps most controversially, delegates and organisations can use their positions to vote against Apple's personnel in elections to leadership positions within internet and web SDOs . It is inconsistent for Apple to hold positions of influence in organisations it works to sabotage, and fellow participants are under no obligation to pretend otherwise. Handing Apple formal or persuasive power within these groups is a mistake, and one that can be corrected without changes to bylaws.],
  [Why Now?],
  [In raising these questions, colleagues have invariably asked "why now? What changed?"],
  [Beyond the threshold point that the damage is cumulative, and therefore it isn't necessary to identify specific instances to discuss the spreading rot, it's fair to ask why anyone should be agitated tomorrow when they might not have been yesterday.],
  [Most of the factors involved have indeed changed very gradually, and humans are famously poor judges of slowly emergent threats. Apple's monopoly on influence, Cupertino's post-2009 WebKit priorities, the suppression of browser competitors, and the never-ending parade of showstopping bugs are all gradually emergent factors. Despite all of this long-running, unrefuted evidence, many continue to think of Apple an ally of the web for helpful acts now more than 15 years old.],
  [But recent events must shake us awake. Apple's petulant attempt to duck regulations, destroy the web as a competitor for good, and frame regulators for the dirty deed was shocking. In recurring misrepresentations to regulators before and since, it has dissembled about its role in suppressing the web, and through its demand for secrecy in quasi-standards processes, has worked tirelessly to cover its tracks.],
  [Taken individually, and in ignorance of iOS's coerced WebKit use by competing browsers, forced monoculture, habitual security failures, and strategic starvation of the Safari team , these shameful acts would simply indicate another monopolist behaving badly. It is only when considered alongside the wider set of facts that the anti-standards strategy and impact become clear.],
  [Do Standards Matter?],
  [Like most who have dedicated the greater proportion of their working lives to the cause of an open and interoperable web, the conclusions offered here shock me as well.],
  [In the end, however, the question "do standards matter any more?" is intrusive, despite my aversion to reconsidering a question whose answer I thought obvious. But in light of the past decade's sidelining of the web, we must grapple with the consequences. To allow Apple to continue to abuse the foundation of standards without acknowledgement would be a failure of honesty towards my own intellectual commitments.],
  [My personal affinity for the many talented and thoughtful people that Apple has sent to standards bodies over the years — including those I think of as friends — has, on reflection, been an emotional blind spot. But here we are. The realisation that they have been an unwitting fifth column against the web is nauseating for me, and I expect many will loudly reject the conclusion. I do not blame them.],
  [For all the harm Apple has done to the web and to competition, I had hoped that it would relent before any of this became necessary. Like most web developers, I harboured hope that, true to Steve Job's promise in '07, Apple would let the web be a "sweet solution" for delivering safe, powerful applications. Piggybacked on that hope was a belief that a relevant mobile web would bolster the relevance of standards. But Cupertino has gone a different way, choosing profit over collaboration and the needs of users.],
  [The web matters too much for the standards-based future it represents to fade without so much as a nod.],
  [Thanks to Kyle Pflug and James Heppell for their thoughtful feedback on drafts of this post.],
  [FOOTNOTES],
  [Or, if you like, "liberaltarian" . ⇐],
  [A faith I do not share. Markets fail frequently, never mind that most goods are hardly substitutable, thinly traded, and lack reliable public prices. All of this means that the information capacity of markets a priori the rationalising effect of standards and market fairness regulation is heavily suspect.],
  [But even for those that take a market fundamentalist perspective, restrictions on trade such as Apple has imposed are offensive to the basic logic of the market's role in bettering society. Only those who would see markets subjugate all, forever, because of one-time power imbalances can be sanguine about what Apple has done.],
  [We do not have to grant pro-totalitarian arguments the assumption of good faith given what we know about where unchecked power leads. ⇐],
  [It is not original to note that there is an inherent contradiction in the idea of liber(al)tarian participants in standards bodies collaborating through non-market mechanisms. We do not have to ignore it, however, or even treat those holding both an affinity to open standards and libertarian ideals as hypocrites, in order to accept that the development of standards is often a creative act of critique for which there is no other functional venue (or, if you like, "market").],
  [Proposals for open internet standards often begin as personal drafts of individual authors, working in a community of like-minded developers experiencing similar challenges and working to design solutions. These proposals are situated in a context that is often opaque to those outside narrow circles, and the communities that form around them trade in reputation as much as any other currency.],
  [In addition to personal status, there is a distinguishable ideology at work:],
  [The open systems ideology that was developed in computing between the 1970s and the 1990s embodied several assumptions articulated in previous open system visions in diplomacy, economics, philosophy, and engineering. These assumptions included:],
  [an economic commitment to global markets;],
  [a moral support of international and multicultural ties;],
  [a political opposition to centralized power — either in governments or in monopolies — that threatened individual autonomy;],
  [a belief that technical professionals could achieve these economic, moral, and political aspirations through cooperation and standardization.],
  [— Andrew L. Russell,
"Open Standards and the Digital Age"],
  [These principles stand as critique to older, less open ways of working. Technology that is more interoperable makes a larger space for critique through code and the market, and that is essential to the openness of any society that depends on software as much as modern, western nations do today. ⇐],
  [The history of Bell Labs, the antitrust battles of IBM, the birth of Unix, and the expectations of "common carrier" treatment for data transmission help to situate the thinking of participants in setting up the foundational standards bodies that we now take for granted. Major battles were fought to keep computing out of the hands of a few corporations with outsized power, and the consequences continue to reverberate.],
  [It is my personal view that it has been the good work of antitrust and anti-monopoly reformers — both within and outside government — that made it possible for other parties to believe in the abstraction of functional markets. Functioning markets are not, in fact, self-organising, and are enabled explicitly by law that helps to minimise noise in the channel (e.g., from fraud).],
  [That self-identified libertarians (along with the rest of society) have benefited dramatically from the gains enabled by these anti-monopoly regimes is not in doubt; the only mystery is how fervently some cling to the belief that regulation must be problematic as a way to skip past its content and ignore engaging on substance. ⇐],
  [Without an "all clear" signal for explicit standardisation, antitrust law in most advanced nations would explicitly forbid the sorts of coordination among industry peers that standards bodies facilitate. Authorities permit, and even encourage, standardisation in contrast to other forms of collaboration because the positive externality benefits of reduced friction to trade from interoperability is so compelling. For more on the history and structure of this now-international regime, see Russell (2014) ⇐],
  [One needs to look no further than tech CEOs lining up to hail the rise of explicitly fascist leaders and ply them with gifts, to understand the ways in which this corruption corrodes our hopes for open, tolerant societies. ⇐],
  [This is not an accusation to be levelled lightly, and not without overwhelming evidence. But that evidence has accrued, and so I feel compelled to speak.],
  [Apple are known both to be capricious and retributive, and its antipathy towards Khronos provides an excellent example of the decade-length grudge-holding for which Cupertino is infamous. I therefore write this post advisedly and with trepidation. ⇐],
  [More than twenty years into the experience of Open Source as a force in software, we can clearly discern that the licence of source code is not, in-and-of itself, a solution to the imbalances inherent in software's relationship to users, or even to other parties with the capacity to develop software.],
  [I believe that history demonstrates clearly that (F) OSS licensing and effective governance are only related by the intellectual and commercial commitments of those building software, and are therefore easily co-opted by wealthy and powerful firms.],
  [We have witnessed the limits of forking as a bulwark against bad behaviour, through both the persistent upward reach of firmware into "open" systems, and through capture in higher layers due to the carrying costs of complex systems. Licensing has also been little help in courts against large and determined enemies of OSS and the freedoms it attempts preserve. The limits of licensing, and the lack of IP defence pooling inherent in common licences, create risks that successful firms and projects hit regularly.],
  [At the limit, (F) OSS licensing is not a significantly disruptive force against wealthy and powerful technology firms, but rather a tool that is useful to peer-level adversaries. For OSS licences and defences to have purchase in practice, a significantly endowed group of technologist's interests must be at stake. The interests of informed and financially capable technologists and the firms that use their software bear only passing resemblance to the needs and interests of society more broadly.],
  [From this perspective, we can understand (F) OSS as complementary to standards development, but unable to fully replace standards-based interoperability as an attenuating force on the power of software in the lives of users. Standards retain a unique ability to build space for challengers within and between proprietary products, which (F) OSS do not. The power of SDOs to pool the patent interests of proprietary players has parallels in (F) OSS , but with more clarity and lower risk, further accelerating practical interoperability.],
  [Therefore, we must understand that it is a rhetorical and intellectual trap to consider (F) OSS a replacement for standards. Each hasten interoperability and attenuate power in different and complementary — but not substitutable — ways, and both mechanisms are healthier when the other succeeds. ⇐],
  [The EC, having borne witness to Apple's appalling behaviour within its borders, and more generally to boot, was having none of it.],
  [The full finding (PDF) is a masterclass in even-handed consideration, and as such it is not surprising that Apple's legal and marketing fictions failed. ⇐],
  [Helpfully for Apple, the conversation around privacy and technology has barely progressed past Apple's anti-Google and anti-Facebook kayfabes.],
  [Privacy advocates are regularly taken in by Apple's marketing, and the tech press remains in a largely stenographic mode. None of this is to say that Google or Facebook are good actors (they are not), only that Apple is also not on the level.],
  [We can begin an analysis by noting that Apple does not encourage users to move their computing to the web where browsers can attenuate the worst invasions of privacy. Browsers do not provide nearly as much information to trackers as even the most locked-down native app in Apple's ecosystem, and Apple know this.],
  [Next, Apple has not funded lobbying and regulatory outreach efforts to establish privacy laws worth a damn. Instead, it channels huge amounts into defeating right-to-repair legislation and defeating browser engine choice around the world, including going as far as funding astroturf groups to provide Cupertino's views in stereo.],
  [Moreover, Apple takes no responsibility for its historical role in the growth of tracking via the native API surfaces Apple created relative to the web. Nor does it demand audits of data use by App Store participants, or to even set policy about acceptable uses of data collected via App Store-vended applications.],
  [Apple does not even forbid pervasive "ad blocker blocking" by the worst actors in its ecosystem, even when interventions are trivial from a policy and technical perspective.],
  [That all of this aligns with Apple's preference for control over, and taxation of, developers cannot escape comment. It further forces us to entertain the idea that Apple's position as a defender of privacy is a cynical show, or that it is incompetent in assessing privacy risks, or that it is out of touch with the behaviour of snooping developers. Any of these would be enough to judge it an incompetent regulator, asleep at the switch.],
  [Depressingly, these are not even exclusive choices. ⇐],
  [It is prima facie evidence of bad faith for a vendor that skims as much cash from the open web as Apple does , and which insists it must maintain a monopoly on browser engines, to object to providing implementations of proposals that other vendors have shipped safely for years, without offering their own designs to address similar needs,],
  [By failing to engage in solving problems, then citing its own objections as reason not to implement the resulting demonstrably safe features, Apple have cut the legs out from underneath any protection from critique. ⇐],
  [Platforms are in competition.],
  [It cannot escape notice that Apple's undermining of voluntary adoption most damages interoperable platforms that might challenge the App Store-based native app ecosystem which supports Apple's vertical integration agenda. ⇐],
  [Here we must mention other instances of operating systems imperilling browser choice. Microsoft, for instance, was credibly accused of making text less readable on Netscape Navigator.],
  [Google, for its part, introduced ChromeOS without any provision for competing browsers. Subsequently, it allowed Android versions of competing browser products using their own engines to register as the default system browser. This is an unsatisfying solution, as Play-based apps are a poor experience on low-end devices and competing browsers are prevented from integrating as deeply as Chrome does. This may not rise to the level of Apple or Microsoft's acts as ChromeOS remains a niche product, ranks lowest in influence, and features a capable browser — regardless, the precedent, combined with prior episodes of Microsoft and Apple turning away from their successful and capable browsers, remains troubling. ⇐],
  [No company in the world is more aware of the awesome power and capability of Apple's A-series chips than Apple itself.],
  [Apple executives know, for instance, that even the least expensive iPhone produced in the past five years is hundreds of times faster than the first iPhones which gave rise to resource-based restrictions on engine choice. They are either aware, or can trivially deduce, that there is no legitimate system health or resource-related reason to disallow competing browser engines. ⇐],
  [As I have discussed before, Apple economises on the development of WebKit and Safari not only by failing to fund development of web features in a timely way, drafting on the path-breaking work of others, but also through an (over)reliance on OS components in lieu of more easily defended abstractions. This goes much deeper than only needing to support a single family of operating systems; unlike competitors, Apple directly leans on OS systems where competitors rebuild large swaths of the runtime to enable the web where underlying OS APIs are more limited.],
  [The result, for Apple, is reduced headcount and a lower bill-of-materials when producing devices (read: higher profits), owing to higher code page sharing across applications.],
  [The consequence for users is an implementation monoculture and slower patch delivery, harming security. Apple's users remain vulnerable to attacks for longer and without recourse to competing alternatives with stronger track records. The downside of all high modernism is brittleness, borne of uniformity, and iOS is no exception. The lack of the ecological diversity that Apple demands undermines security and resilience. This is not a price society should pay for the convenience of a blue chat bubble. ⇐],
  [In testimony before various competition authorities around the world, and in peevish screeds in response to those arguments failing, Apple habitually attempts a rhetorical redirection that unmasks its anti-Popperian thirst for control.],
  [It appears to believe, on the strength of brand, that it can win on the ground of "who should rule?," rather than "how can institutions keep bad rulers from doing too much damage?" In so doing, Apple offers an authoritarian model of technology. Cupertino proposes that all sources of control attenuation are themselves totalising, and any compromise forced on the ruler therefore equivalent to a coup.],
  [This is nonsense, both practically and historically, and technologists that support democratic norms should reject this framing.],
  [History shows clearly that open systems in open societies enable civil society to take many effective positions that attenuate untrammelled power, both of the state and of other actors. We can further see that neither open nor closed systems are full bulwarks against government coercion. The prospects for improved societies must not be invested in autocratic technology firms for the simple reason that they are powerless to deliver it.],
  [Apple itself has been forced to compromise in areas such as right-to-repair without any of the apocalyptic prophecies of Cupertino's lobbyists coming to pass.],
  [Here Apple, and its extremely vocal band of apologists, will bring up overreaches by others, including disastrous and ill-advised anti-encryption pushes by national governments. The goal of this argument is to sully the idea of democratic control of technology. "How" , it asks leadingly, "can anyone trust these people to do what's right for users?"],
  [How indeed! For the central point is that we do not have to. Recourse is available (in functioning democracies) through elected representatives and the responsiveness to citizen's concerns. We can even accept that democracies will get many of these issues wrong for a time without seceding any ground to Apple's authoritarian offer. It is intellectually consistent to reject both noxious positions taken by elected officials and offers of high modernist control by firms opposed to the current positions of a government.],
  [Apple's arguments are microns deep on the merits. They attempt to erase both the successes of civil society (rather than Apple) in curbing abuses along with Apple's own shameful track record of capitulation to overtly authoritarian regimes. 20],
  [Apple's framing asserts that total control by a famously unaccountable firm is a Panglossian utopia. That any decision Cupertino makes now, has ever made, or has ever reversed, have unquestionably been the best of all possible options. That by paying a thousand dollars for a phone, we are but lucky to bask in the glow of such resplendent wisdom.],
  [It's all too much to take, at least for anyone with a working memory. As I hope I have demonstrated here, this posture fails on ethical as well as practical grounds.],
  [Apple, with all of its power and money, could be an ally to civil society in curbing abuses without claiming total and unaccountable control for itself in the process. It is incumbent on any thinking technologist to reject such land grabs, even when they come wrapped in causes we otherwise support. To do otherwise is to co-sign the doctrine of "who should rule?," a framing that is caustic to both our short-term technical and long-term societal interests. ⇐],
  [Paradoxically, it may be Apple's own malign behaviour regarding browser choice that might prevent a "no browsers" policy from being possible today.],
  [Even if we were to ignore Cupertino's incentive to maintain browsers on iOS owing to the shockingly large flows of money from Google for search placement (which Apple records as nearly pure profit), regulators may require it to pursue an "all browsers" alternative to fairly redress the harms from the previous 15 years of abuses. Should this come to pass, Cupertino would (again) have no party to blame but itself. ⇐],
  [The damage Apple has done to the cause of internet and web standardisation is analogous to the (US) concept of impeachable "high crimes and misdemeanours" , rather than better enumerated, more pedestrian infractions. This category covers acts that are destructive to the foundational principles of the enterprise, regardless of narrow legality.],
  [Internet SDOs are not set up well to police or react to this class of offence, which may help explain why Apple's violence against the community has gone unremarked for so many years. ⇐],
  [Apple engineers should be questioned (politely, but insistently) about timelines for implementation of any feature that any other engine chooses to ship, and failure to provide that timeline should be viewed as ongoing evidence of malfeasance against the internet and web community for as long as Apple withholds the ability for others to bring their own engines and whatever features they choose.],
  [If this causes Apple to retreat from sponsoring work in these venues, that is regrettable, but must also be understood as a choice that is entirely within Apple's power to reverse. ⇐],
  [The fuller airdrop story creates a cross-pressured narrative in which it is possible to claim that Apple was acting to protect, rather than suppress, A4 protesters. But such a pose must also contend with Apple's own history of failure, first to build a truly private version of a system marketed in those terms, thereby encouraging users in sensitive situations to expose themselves to great risk. Second, Apple's unwillingness to patch post-disclosure.],
  [Owing to AirDrop's use of closed protocols that Apple does not make available to developers of competing applications, it also falls exclusively on Apple's shoulders that better solutions were not available to replace Apple's own botched implementation.],
  [The story is more complex than "Apple sold protesters up the river," but no publicly available version of events is a defence the argument that Apple is a bellicose marketing outfit with a situational and opportunistic relationship to user privacy and security.],
  [When the effect is to expose or debilitate users that rely on the very properties Apple so truculently asserts its competitors fail to deliver, it becomes impossible to defend Cupertino's insistence that it alone should be trusted. ⇐],
),
  insert-map: (:),
  word-count: 7187,
  edited-for-length: false,
  debug-mode: false,
)


#article-row((
  [
    #standard-article(
  title: [Becoming America],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [When the United States of America was founded, it was only a union of a small number of states. By the beginning of the 20th century, the United States had become an empire; with states and territories and colonies that spanned the globe. As a result, the country began to not only reconsider its place in the world, but also its very name.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 103,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    #standard-article(
  title: [dbVar December 2020 Release],
  author: [PubMed Health],
  source-name: [PubMed Health],
  images: (),
  paragraphs: (
  [​ d bVar December 2020 Release],
  [Summary:],
  [December 2020 Release New/updated studies: 4
New Variant regions: 95356
New Variant calls: 103281
Non-Redundant Deletions: 2,563,576
Non-Redundant Duplications: 433,664
Non-Redundant Insertions: 1,308,484],
  [dbVar Resources:],
  [Study Browser 
 Human Data Hub 
 Organism List 
 FTP files 
 Tools for analyzing dbVar data 
 Non-Redundant Structural Variants],
  [New/updated studies:],
  [Study: nstd186 (NCBI Curated Common Structural Variants)],
  [Description: A curated dataset of all structural variants in dbVar that meet the following criteria: were part],
  [of a study with at least 100 samples; included allele frequency data; had an allele frequency of],
  [become available. See Variant Summary counts for nstd186 in \[dbVar Variant],
  [Summary|/dbvar/content/var\_summary/\#nstd186\]. See the latest statistics for nstd186 in \[Summary of],
  [nstd186 (NCBI Curated Common Structural Variants)|/dbvar/content/common\_summary\].],
  [Organism: Human(9606)],
  [Study Type: Control Set],
  [Submitter: NCBI dbVar Curated (NCBI)],
  [Variant Calls: 61086],
  [Variant Regions: 55981],
  [FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
  [Study: nstd194 (Lee et al 2020)],
  [Publication: Lee et al. 2020],
  [Description: To systematically identify non-reference insertion structural variants among human populations, we],
  [developed an insertion detection pipeline, InserTag, which generates unmapped contigs by local],
  [de-novo assembly and then infers the full-sequence of insertion variants by tracing the contigs],
  [from non-human primates and other human assemblies. By application of the pipeline to 1000 Genomes],
  [Project database, we could identify 1,696 non-reference insertion variants in 2,535 individuals and],
  [re-classify the variants as retention of ancestral sequences or novel sequence insertions based on],
  [the ancestral state. Here, we report 1114 variants which are larger than 100 bp and have genotypes.],
  [See Variant Summary counts for nstd194 in \[dbVar Variant],
  [Summary|/dbvar/content/var\_summary/\#nstd194\].],
  [Organism: Human(9606)],
  [Study Type: Collection],
  [Submitter: Jin-young Lee (Yonsei University)],
  [Variant Calls: 1114],
  [Variant Regions: 1114],
  [FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
  [Study: nstd198 (Hanlon et al 2021) 
Description: Genotyping inversions using a Bayesian binomial model (InvertypeR) and Strand-seq data published by
 the Human Genome Structural Variation Consortium (\[Chaisson et al.
 2019|https:\/\/doi.org/10.1038/s41467-018-08148-z\],\[dbVar
 nstd152|https:\/\/www.ncbi.nlm.nih.gov/dbvar/studies/nstd152/\]). Samples used: HG00512-4, HG00731-3,
 NA19238-40. See Variant Summary counts for nstd198 in \[dbVar Variant
 Summary|/dbvar/content/var\_summary/\#nstd198\].
Organism: Human(9606)
Study Type: Collection
Submitter: Vincent Hanlon (University of British Columbia)
Variant Calls: 3053 
Variant Regions: 234 
BioProject: PRJNA679815 
FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
  [Study: nstd199 (Quan et al 2021)],
  [Description: Structural variation (SV) acts as an essential mutational force shaping the evolution and function],
  [of the human genome. To investigate the role of SVs in high-altitude adaptation (HAA), we here],
  [generated a comprehensive catalog of SVs in a Chinese Tibetan (n = 15) and Han (n = 10) population],
  [using the nanopore sequencing technology. Among a total of 38,216 unique SVs in the catalog, 27%],
  [were sequence-resolved for the first time. See Variant Summary counts for nstd199 in \[dbVar Variant],
  [Summary|/dbvar/content/var\_summary/\#nstd199\].],
  [Organism: Human(9606)],
  [Study Type: Collection],
  [Submitter: Cheng Quan (Beijing Institute of Radiation Medicine)],
  [Variant Calls: 38028],
  [Variant Regions: 38027],
  [BioProject: PRJNA681146],
  [FTP: https:\/\/ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo\_sapiens/by\_study],
),
  insert-map: (:),
  word-count: 472,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    #brief-group((
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following journal has been added to the PubMed Central archive:
 
Journal Title: Canadian Urological Association Journal
ISSN: 1911-6470 (print)
URL: http:\/\/www.pubmedcentral.nih.gov/tocrender.fcgi?action=archive&journal=552 
Archive includes: v. 1 (2007) to the present. There is no embargo delay for this journal.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [NHLBI TOPMed: Determining the Association of Chromosomal Variants with Non-PV Triggers and Ablation-Outcome in AF (DECAF) ( study page | release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [
 NIH RECOVER: A Multi-Site Observational Study of Post-Acute Sequelae of SARS-CoV-2 Infection in Adults
  
 ( study page 
 |
 release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [

​The PubMed journals translation table has been updated to include journal names without initial articles such as: the, le, la, a, an, etc. This means that such journal titles can now be searched with or without initial articles and they will map to the appropriate journal.​])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [​ Genomic Data Archive From the Network for Pancreatic Organ Donors With Diabetes
  
 ( 
 study page 
 
 |
 
 release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Hindawi has been added to PubMed Central:
 
International Journal of Endocrinology 
ISSN: 1687-8337 (print) 1687-8345 (electronic)
 http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/995\/   
Archive includes: v. 2009(2009). 
Note: There is no embargo delay for this title.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Medknow Publications has been added to PubMed Central:
 
Ancient Science of Life
ISSN: 0257-7941 (print); 2249-9547 (electronic)
URL: http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1769\/ 
Archive includes volume 1 (1981) to volume 30 (2011)
Note: There is no embargo delay for this journal.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from SAGE-Hindawi has been added to PubMed Central:
 
Autoimmune Diseases 
ISSN: 2090-0430 (electronic)
 http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1390\/    
Archive includes: v. 2010(2010)
Note: There is no embargo delay for this title.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Frontiers Research Foundation has been added to PubMed Central:
 
Frontiers in Human Neuroscience
ISSN: 1662-5161 (electronic)
URL: http:\/\/www.pubmedcentral.nih.gov/tocrender.fcgi?action=archive&journal=645 
Archive includes vol. 1 (2007) to vol. 2 (2008). Current content is forthcoming.
Note: There is no embargo delay for this journal.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The scanned archive is complete for the following journal:
          Journal title:   Annals of The Royal College of Surgeons of England
ISSN: 0035-8843 EISSN: 1478-7083
URL: http:\/\/www.pubmedcentral.nih.gov/tocrender.fcgi?action=archive&journal=386 

The scanned archive includes vols. 1-84 (1947-2002). The archive also includes vols. 85-89 (2003-2007) and current content is forthcoming.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Hindawi has been added to PMC:

Schizophrenia Research and Treatment
ISSN: 2090-2085 (print) 2090-2093 (electronic)
http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1885
Archive includes: v. 2011(2011) - v.2012(2012)
Note: There is no embargo delay for this title.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The Consensus Coding Sequence (CCDS) update for mouse build Mm38.1 was released earlier this week, and this update is now reflected in Gene as well. This update adds 958 new CCDS IDs, reinstates 1 previously withdrawn CCDS ID, and adds 506 Genes into the mouse CCDS set. Mouse build 38.1 includes a total of 23,027 CCDS IDs that correspond to 19,945 GeneIDs.

For information about CCDS, please visit: http:\/\/www.ncbi.nlm.nih.gov/projects/CCDS])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Sultan Qaboos University has been added to PubMed Central.
 
    Sultan Qaboos University Medical Journal
    ISSN: 2075-051X (print) 2075-0528 (electronic)
    URL: http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1460\/    
    Archive includes: v. 5 (2003) to v. 11 (2011). Earlier content is forthcoming and will have no delay.
 
Thanks,
PubMed Central])],
      [#brief-item([Robin Ward (eviltrout)], source-name: [Robin Ward (eviltrout)], [The Roottrees are Dead was released on January 15, 2025 and
it did much better than I ever expected. The reception has been amazing. In just over a week, the game hit the magic mark of 500
reviews on Steam, and triggered the “Overwhelmingly Positive” status.

On BlueSky, Bloomberg writer Jason Schreier blew me away when he posted :

“Seven days into 2025 and I’ve already played what I suspect will be one of my favorite games of the year: The Roottrees Are Dead.” Wow!])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [Integrative Clinical Sequencing Analysis of Metastatic Castration Resistant Prostate Cancer Reveals a High Frequency of Clinical Actionability
  
 ( 
 study page 
 
 |
 
 release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from the Association of Chiropractic Colleges has been added to PubMed Central. Journal of Chiropractic Education ISSN: 1042-5055 (print) http:\/\/www.pubmedcentral.nih.gov/tocrender.fcgi?journal=604&action=archive Archive includes v. 20 (2006) to v. 22 (2008) Note: There is no embargo delay for this journal PubMed Central])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [

If you use the gene2xml utility to read files from the ASN\_BINARY directory on the Gene FTP site, please download the latest revision (1.5) here . This update will be needed to read new data elements that will be added to the ASN.1 in the near future.

To see which version of gene2xml you are currently using, simply run gene2xml with a single hyphen as a parameter.​])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [

​The ability to create an RSS feed is available in the new PubMed.  The RSS feature returns complete search results and no longer uses the My NCBI "What's New" strategy that is used for saved search alerts.
​])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [​ Lineage Plasticity and Immune Cell Heterogeneity Are Coordinately Dysregulated Through Changes in FOXA1 Expression in Bladder Cancers with Squamous Differentiation
  
 ( 
 study page 
 
 |
 
 release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from BioMed Central has been added to PubMed Central:

Scandinavian Journal of Trauma, Resuscitation and Emergency Medicine
ISSN: 1757-7241 (electronic)
 http:\/\/www.pubmedcentral.nih.gov/tocrender.fcgi?journal=707&action=archive 
Archive includes volume 16 (2008)
Note: There is no embargo delay for this journal])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The SRA database contains genome sequence reads for one isolate ( Accession: SRX067313 ) and a preliminary genomic assembly of another isolate in the Nucleotide database ( Accession: AFOB00000000 ).])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [NHLBI TOPMed: Genomic Summary Results for the Trans-Omics for Precision Medicine Program
  
 ( 
 study page 
 
 |
 
 release notes )])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [ClinVar's monthly data release is now available.

 Please note the following documents on our FTP site ( ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar\/ ):

Complete XML extraction: ClinVarFullRelease\_00-latest.xml.gz at ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar/xml\/ 

VCF files: clinvar\_00-latest.vcf.gz at ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf\/ .

Tab-delimited variant- and gene-specific summaries: ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar/tab\_delimited\/ .

Release notes: ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar/release\_notes\/ 

Modifications to the xsd: clinvar\_public\_diff at ftp:\/\/ftp.ncbi.nlm.nih.gov/pub/clinvar/release\_notes\/ 

 Please note the following documents on our web site: 

Current statistics: http:\/\/www.ncbi.nlm.nih.gov/clinvar/submitters\/ 

Please contact us at clinvar\@ncbi.nlm.nih.gov if you have any questions.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [

​An updated version of PubMed is now available at  https:\/\/pubmed.ncbi.nlm.nih.gov\/ . The new PubMed will become the default in spring 2020 and will ultimately replace the legacy version.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [

​In order to provide a less-cluttered PubMed results display, the status tag lines, e.g., \[PubMed - as supplied by publisher\], were removed from the Summary results. Other display formats were not modified.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Hindawi has been added to PMC:
 
ISRN Hematology
ISSN: 2090-441X (print) 2090-4428 (electronic) 
 http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1638\/ 
Archive includes: v. 2011(2011)
Note: There is no embargo delay for this title.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [The following new journal from Nature Publishing Group has been added to PMC:
Translational Psychiatry
2158-3188 (EISSN) 
URL: http:\/\/www.ncbi.nlm.nih.gov/pmc/journals/1761\/ 
Archive includes volumes 1-2 (2011-2012) and current content is forthcoming.
Note: There is no embargo delay for this journal.])],
      [#brief-item([PubMed Health], source-name: [PubMed Health], [Whole Exome Sequencing and RNA Sequencing of High Grade Serous Ovarian Cancer in Black and White Patients
  
 ( 
 study page 
 
 |
 
 release notes )])],
    ))
  ],
), ruled-indices: (1, 2,))

#article-row((
  [
    #standard-article(
  title: [We The People: Canary in the Coal Mine],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [The Third Amendment. Maybe you've heard it as part of a punchline. It's the one about quartering troops — two words you probably haven't heard side by side since about the late 1700s.],
  [At first glance, it might not seem super relevant to modern life. But in fact, the U. S. government has gotten away with violating the Third Amendment several times since its ratification — and every time it's gone largely unnoticed.],
  [Today on Throughline's We the People : In a time of escalating political violence, police forces armed with military equipment, and more frequent and devastating natural disasters, why the Third Amendment deserves a closer look.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 147,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    #standard-article(
  title: [What Happened After Civilization Collapsed],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [What happens after everything falls apart? The end of the Bronze Age was a moment when an entire network of ancient civilizations collapsed, leaving behind only clues to what happened. Today, scholars have pieced together a story where everything from climate change to mass migration to natural disasters played a role. What the end of the Bronze Age can teach us about avoiding catastrophe and what comes after collapse.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 109,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#colophon([The Critical Dispatch], [Vol. 1, No. 052], [2026-03-30])
