// Generated by OffScroll Typst renderer
// Edition: Quiet Tribune — 2026-03-30

#import "templates.typ": *

#set page("us-letter",
  margin: 0.5in,
  footer: context {
    if here().page() > 1 {
      set text(7pt, font: "Source Sans 3", fill: luma(153))
      line(length: 100%, stroke: 0.5pt + luma(204))
      v(0.05in)
      align(center)[Quiet Tribune \u{2014} 2026-03-30]
    }
  }
)

#set text(10pt, font: "Source Serif 4", fill: luma(26), hyphenate: true)
#set par(justify: true, leading: 0.52em)

#masthead([Quiet Tribune], [Vol. 1, No. 010], [2026-03-30]
)

// --- Front Page Feature ---
#feature-article(
  title: [How to use GasBuddy to beat rising fuel prices],
  kicker: [Cover Story],
  author: [Rachel Craft and Andrew Kunesh],
  source-name: [The Points Guy],
  deck: [class="rssBody"\>

The conflict in the Middle East has sparked a surge in fuel prices , meaning both daily commutes and summer road trips are getting more expensive.],
  lead-pre: [],
  lead-cap: [c],
  lead-rest: [lass="rssBody"\>],
  body-paragraphs: (
  [The conflict in the Middle East has sparked a surge in fuel prices , meaning both daily commutes and summer road trips are getting more expensive.],
  [Thankfully, you can save money on gas by enrolling in loyalty programs offered by major gas companies. That said, your favorite chain may not have the best prices, even with loyalty discounts — or it may not have stations along your road trip route. That's where GasBuddy comes in.],
  [GasBuddy is an app that helps find the cheapest gas near you. Even better, the program's Pay with GasBuddy+ feature can save you more than 20 cents per gallon. Read on to learn everything you need to know about saving money on gas with GasBuddy.],
  [Related: 7 tips to get the most out of a tank of gas],
  [The GasBuddy app shows prices at all stations nearby to help you find the best deal on gas. Just download the mobile app and let it see your current location. You can filter by which fuel type you'd like to buy and how far you're willing to drive for gas.],
  [GASBUDDY],
  [There's also a map view.],
  [GASBUDDY],
  [Tap on a gas station to see its pricing for each type of gas. GasBuddy relies on crowdsourcing for pricing data, so prices may not always be accurate. However, we've found that most stations are updated at least once per day; you can see the last update time below the price.],
  [GASBUDDY],
  [GasBuddy will also alert you to flash deals, which you can activate in the app. Some of these require having a membership with the gas station, like this one through Fuel Rewards.],
  [GASBUDDY],
  [GasBuddy can save you money on regular fill-ups, but it's especially useful during long road trips when you need to fill up in unfamiliar locales.],
  [Related: Route 66 road trip planner: The best stops along the way],
  [When you enroll in Pay with GasBuddy+ and link a bank account, you'll receive a free card in the mail that you can use to pay at the pump anywhere Mastercard is accepted. Transactions will be charged to your linked bank account, and any available discounts will automatically be applied.],
  [GASBUDDY],
  [There are two types of membership. The Standard plan is free to join and guarantees savings of at least 3 cents per gallon, though you may save up to 25 cents per gallon depending on where you fill up. You can save even more with a Premium plan — more on that in a moment.],
  [GASBUDDY],
  [Here are some tips to help maximize Pay with GasBuddy+.],
  [Enroll in a Premium membership if you drive a lot],
  [The Premium option, which costs \$9.99 a month or \$99 a year, promises savings of at least 20 cents per gallon (on the first 50 gallons monthly, then 5 cents per gallon). Furthermore, Premium members have access to 24-hour roadside assistance from Allstate (twice per year).],
  [It may be worth paying for a Premium membership if you know you're going to drive a lot in a given month. Do the math beforehand to ensure you'll get enough value to offset the fee.],
  [Stack with gas loyalty programs],
  [One of the best features of Pay with GasBuddy+ is that you can stack it with other fuel rewards programs.],
  [For example, you can still enter your Fuel Rewards number at the pump when you use your Pay with GasBuddy+ account. Fuel Rewards Platinum members save 10 cents per gallon at Shell stations, meaning GasBuddy Premium members can theoretically save over 30 cents per gallon at some gas stations.],
  [Related: How to maximize savings with a Shell credit card],
  [Stack with GasBuddy Rewards],
  [Another part of the app, GasBuddy Rewards, lets you earn points by taking surveys, playing games, watching videos, dining out, snapping receipts and more.],
  [GASBUDDY],
  [You can redeem points for digital gift cards or, if you have a Pay with GasBuddy+ membership, redeem them toward additional savings on gas. Two thousand points equate to 10 cents off per gallon, and the savings will automatically apply to your next fill-up.],
  [GASBUDDY],
  [Related: Best road trips in the US],
  [ISSARAWAT TATTONG/GETTY IMAGES],
  [One downside to Pay with GasBuddy+ is that you must pay with your GasBuddy card, which essentially works like a debit card, so you'll miss out on any credit card rewards. However, depending on which cards you have in your wallet and the savings you can get through GasBuddy, it might make sense to choose GasBuddy.],
  [For instance, the Citi Strata℠ Card (see rates and fees ) earns 3 ThankYou Rewards points per dollar spent on gas purchases. Since Citi points are worth 1.9 cents apiece in our March 2026 valuations , that's a return of 5.7%. If you find a station where GasBuddy offers 6 cents or more off, paying with your GasBuddy card makes more sense.],
  [You might consider keeping your GasBuddy card in your wallet alongside one of our top-earning credit cards for gas purchases . Then, every time you fill up, you can do the math to see which offers the best return.],
  [Related: Best credit cards for gas purchases],
  [GasBuddy is a great way to save on fuel, especially when prices spike. Download it and request a Pay with GasBuddy+ card before your next big road trip, and don't forget to stack it with other fuel rewards programs. After all, every cent per gallon counts.],
  [Editorial disclaimer: Opinions expressed here are the author’s alone, not those of any bank, credit card issuer, airline or hotel chain, and have not been reviewed, approved or otherwise endorsed by any of these entities.],
),
  edited-for-length: false,
)

#pull-quote([Furthermore, Premium members have access to 24-hour roadside assistance from Allstate (twice per year).], [Rachel Craft and Andrew Kunesh])


{
  #section-label([Features])
  #standard-article(
  title: [SARATOGA FAMILY, The Ultimate Holiday Gift for Your Family: A VACATION!!],
  author: [Anne Gordon],
  source-name: [Live Life Travel],
  images: (),
  paragraphs: (
  [The Ultimate Holiday Gift for Your Family: A VACATION!!],
  [It may be cliché, but also very true, the best gift that you can give your family (especially your children) is the gift of time. And what better way than traveling the world as a family.],
  [4 TIPS FOR PLANNING ANY TYPE OF FAMILY TRAVEL],
  [1) PLAN AHEAD – It’s never too early to start planning],
  [Tip: Airfare goes on sale 11 months in advance; We like the Hopper APP to track airfare prices],
  [2) DON’T WAIT – Start them young; they grow up way too fast],
  [3) ENGAGE – Let them be part of the decision; Inclusive family decisions always make every trip much more successful.],
  [4) EDUCATE – Don’t tell the kids, but traveling the world is a totally super fun way to learn all of that “stuff” that they teach you in school.],
  [Tip: The SSCD kids learn about Ancient Rome, Greece, China, India and Egypt in the 6th Grade, we recommend taking them to these magnificent destinations after the 6th Grade.],
  [LIVE LIFE TRAVEL’S TOP PICKS FOR FAMILY TRAVEL],
  [BEACHES TURKS AND CAICOS – To us, this is comparable to what Disney World is to the rest of American children (but way better!); Contact us to receive your \$250 spa credit],
  [Tip: We recommend booking 1-2 years in advance for this property (for high season weeks); there are 2 other Beaches located in Jamaica (Negril and Ocho Rios); we love them all],
  [ITALY – Ancient Rome is really something spectacular, especially after learning about it in 6th grade, we think that Italy is a trip that the entire family can enjoy; We also highly suggest heading down to Sicily, a hidden gem],
  [AFRICAN SAFARI – A must for every family; truly a once in a lifetime experience. We recommend the Cape Town – Sabi Sands – Victoria Falls combo if you want to do it right.],
  [HAWAII – A favorite destination for families over the Holiday Break and for good reason! We love the Grand Wailea in Maui and The Four Seasons Hualalai on The Big Island. Experience two very different landscapes as to what Hawaii has to offer],
  [ALASKA – Experience nature up close and personal with Lindblad Expeditions on the National Geographic expedition ships that have custom programs just for kids],
  [FOUR SEASONS RESORTS – In general, you just cannot go wrong, and we love them. Our top family choices are Nevis, Costa Rica, Anguilla, Chiang Mai and Langkawi.],
  [OUR \#1 FAMILY TRAVEL RECOMMENDATION: GLOBAL CITIZENS WANTED],
  [ME to WE – A new travel partner to our Virtuoso family, this company is one of our very favorites. We would encourage you all to please check out their video on our Facebook and Instagram pages. If you want to make a difference in the world, if you want to make an impact with your children, if you want to create lifelong memories and a feeling that will never fade away, then ME to WE is what you are looking for. Travel itineraries currently include Ecuador, Kenya and India. Contact us to learn more!],
  [52% of Americans do not take all their PAID vacation time.],
  [style="text-align: left;"\>Please do not become or stay part of this statistic— Vacations are healthy, not only for you physically and mentally, but emotionally for your family, especially for kids. Life is short, make the most of it!],
  [The post SARATOGA FAMILY, The Ultimate Holiday Gift for Your Family: A VACATION!! appeared first on Live Life Travel .],
),
  insert-map: (:),
  word-count: 1202,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Feel-good Lunch Ideas],
  author: [Heidi Swanson],
  source-name: [101 Cookbooks],
  images: (),
  paragraphs: (
  [Coming up with inspired lunch ideas takes some effort. One of the things I’ve been trying to be better about is lunches on-the-go. Often times, let’s be honest, it’s re-marketing leftovers. Too often, if we’re not going to be home for the day, we just wing it. And I’m nearly always sorry we didn’t make the effort to pack a good lunch. This is especially true if we’re on some sort of trip, towing the Airstream . Because on those days parking dictates where you’re lunching. And just thinking about it is making me cringe. So yeah, we’re trying to do better over here and I thought I’d share some recent wins.],
  [Lunch Ideas \#1],
  [These lunch boxes (above) came together pretty quickly. Nearly everything was a leftover, or component of a previous meal. To pull it together I peeled and chile-dusted the hard boiled eggs , sliced the avocado and sliced the mandarin.],
  [1. Spicy Sesame Coleslaw : You’ve seen it before, you’ll see it again. Lol. It’s my favorite coleslaw , and I’ll basically tuck in anywhere. Feathery green and red cabbages along with carrots, apples, and scallions tossed with a spicy, creamy sesame dressing.],
  [2. Pickled Cauliflower : The pop of color you need in your lunch. This quick pickled cauliflower delivers a good amount of tang and crunch in the midst of less structured components. I make mine with chiles, mustard seeds and slivered onion, but you can play around.],
  [3. Chile-dusted Hard-boiled Egg: Here’s how to make these. Combine equal parts chile powder and MDH chana masala powder in a small bowl. I like to use this Kashmiri chillie powder , but use what you have (and like). Hard boil eggs , peel them, rinse, dab each egg a bit on a clean towel to take off excess water, then roll them around in the spice mixture until completely covered. Slice and serve, or pack into lunch.],
  [4. Turmeric-Scallion Tofu Spread : This is actually leftover wonton filling from my last round of wonton soup . But it’s also great as a lettuce wrap filling, cracker and sandwich spread, and on its own. Here, I nestle it into a stack of 2-3 little gem leaves. Get the recipe – it’s the first part of the recipe on this page, minus the wrappers.],
  [5. Red-spiced Edamame : I’ll write this up as its own recipe soon, it’s a homemade spice blend made by crushing Kashmiri chillies, smoked paprika, brown sugar, sesame, dried onion flakes, salt, and a kiss of cardamom together. Sprinkle generously. There are a lot of other spice blend ideas in the Spice \/ Herb \/ Flower \/ Zest PDF that members get. Just about any of those are great here. Experiment!],
  [6. Pepita & Curry Leaf Tadka : I’ve definitely over-stripped my young curry tree making this lately. Toast a cup of pepitas and set aside. Heat 2 tablespoons of oil in a small saucepan over medium-high heat, stir in 50-ish fresh curry leaves. Continue to stir and when the leaves begin to crisp up add 2 teaspoons black mustard seeds. Keep stirring and when the seeds have toasted a bit and stopped popping, add 1/2 teaspoon chile powder. Pour this over your pepitas, toss well, and salt to taste. good on everything, Including the soba in the next lunch.],
  [Also: purple rice, sliced avocado, mandarin wedge, nutritional yeast kale chips],
  [Lunch Ideas \#2],
  [The one component of the lunch boxes (above) that wasn’t made ahead of time, was the soba noodles. I boiled them, and ran them under cold water just before packing up.],
  [6+. Soba with Pepita & Curry Leaf Tadka : The same pepitas as above (lunch ideas \#1), this time tangled with cold soba.],
  [7. Vegan Tamagoyaki : This is a vegan version of tamagoyaki, the much-loved Japanese rolled omelette. I like to make chickpea-tofu version, and this one is lined with nori and seasoned with scallions and herbs. They’re fantastic lunchbox heroes because you can make and roll them ahead of time. They’ll keep for a few day so you can slice and go.],
  [8. Blistered Artichoke Hearts : Leftovers from dinner the previous night. I cooked these from frozen. So easy, so good. I wrote a long post about how to cook artichokes – both fresh and frozen. So, if you love artichokes, but think they’re too much work, read this. Same goes if you think the frozen ones are going to be bad. They aren’t and they’re great in scenarios like this one, quick pastas, casseroles, etc.],
  [9. Fava Beans Tossed with Citrus Olive Oil : These are fava beans that have been shelled, boiled for a flash, shelled again, and then splashed with a bit of lemon olive oil, and tossed with a pinch of salt. From previous dinner. I do the same with edamame, but favas are in season and I they’re worth all the shelling and peeling drama.],
  [10. Kale Chips : Some extra crushed kale chips tossed with the remaining pepitas. My method for epic kale chips is this: buy curly kale, make sure it’s dry if you recently washed it. Toss the kale with olive oil and scrunch it all up with your hands, be sure it’s all coated. Toss with a lot of nutritional yeast, get a good coating going. Season with salt and bake at until the chips at the edges start browning. Toss well. Continue to bake until crispy but still mostly green. Or have a look at this kale chip recipe .],
  [Also: blood orange wedges for dessert.],
  [A Couple Pro-tips],
  [There’s actually just one main tip, but I’ll add more as I think of them. Line your bentos with parchment paper for easy clean-up (pictured below). This isn’t as important with stainless steel containers, they clean up quite quickly. Bentos, often made of cedar, are a bit more fragile and take more care if you want them to last for many years. Also, clean up as soon as you get home. The reset is key to looking forward to your next special box lunch.],
  [More Lunch Ideas: Salads!],
  [Salads are another favorite lunch idea. For the best experience, keep the dressing on the side and toss just before eating. Also, pro-tip, leave a good amount of room or headspace in your salad vehicle, so tossing is contained and less messy. For to-go or desk salads, I love bringing the components for a Nicoise salad or Nicoise-ish salad. The lettuces and other ingredients can stand up to transportation and you get a great mix of protein, greens, and veggies all in one lunch. See photo below.],
  [Bentos : I have (and love) my small collection of bento boxes. They’re beautifully crafted and fit the perfect amount of food. They often come with small dividers to create separation between food, but you can also use lettuce, or other small containers to divide things up.],
  [Tiffins (or dhabbas) : These containers have long been used in India to enable healthful, homemade meals outside the home. I have a circular, triple-stack stainless steel version I love for a number of reasons including durability, compactness, and security. The tiers nestle tightly making spills and accidents unlikely. I have my eye on a rectangular version as well.],
  [Both bentos and tiffins have a tradition of enabling meals made with care and love. And continuing this tradition is something I try to channel when I’m packing a lunch for myself or someone I care about.],
  [I don’t mind mixing different types of lunch containers. And sometimes I’ll make an individual lunch for each person, each in its own container. But, other times I think it’s fine to load up a few family-style containers and do it that way. I think that works great for components that can be more communal, like edamame, or a bunch of dumplings, a stack of paratha, vegan sushi or quesadillas, quinoa patties , etc.],
  [Hot Lunch!],
  [Use a thermos to bring hot miso soup or tea or rasam or whatever else you can think of. This is always the icing on the cake and unfailingly makes me happy (or happier!) When I really have things lined up, I’ll bring green tea, miso soup, or soba tea and a durable glass or two wrapped in cloth. Simply rewrap when you’re finished.
 
I hope this provides a bit of inspiration! It’s really wonderful to take a bit of time to sit down to a thoughtfully prepared, healthful homemade lunch and I’m never sorry about making the extra effort (in the long run). Even if it can make a morning a bit more demanding than usual, I know when I do it, I’ll eat better, feel better, and get excited about sitting down to lunch. Enjoy! -h],
  [Vegetarian Lunch Ideas : One Sauce, Three Lunches],
  [Continue reading Feel-good Lunch Ideas on 101 Cookbooks],
),
  insert-map: (:),
  word-count: 1511,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Ballsfest and Live Life Travel partner],
  author: [Anne Gordon],
  source-name: [Live Life Travel],
  images: (),
  paragraphs: (
  [From the moment a parent hears the words “Your child has cancer,” their lives are forever changed. Life as they knew it quickly turns into a world of unknowns, worry, and fear, and strikes a stifling blow as the saying “Life can change in an instant” becomes a reality. A cancer diagnosis takes a tremendous toll on a family, emotionally, socially, physically, and financially. This is where the nonprofit Ballsfest comes into play. With their mission to lift the spirits of children, teens, and families battling childhood cancer, they strive to provide unique gifts and experiences, as well as year-round programs and services to help ease the stress and strain felt by families.],
  [Recognizing the importance of remaining positive, enjoying the moment, and creating memories, Ballsfest has provided families with unique travel experiences to do just that. We have found a partner who genuinely shares all of these same motivations with a mission that is stated clearly within the company’s name, one that she lives by herself and encourages others to as well, Live Life Travel . While already focusing on family travel locally in Saratoga Springs, NY, the partnership was a perfect fit.],
  [Anne Gordon, owner of Live Life Travel, LLC stated that “It is my belief that all families should prioritize time together, live life to the fullest, and spend as much time as possible creating family memories (while also unplugging). Having the chance to see the pictures of Evan and his family and how happy they were, (Evan’s Universal trip in January 2019 was the partnerships first collaboration together) is exactly why I love my job so much. Seeing Evan’s smile on a trip that I had the privilege of planning was just an incredible feeling of joy and I am really looking forward to creating more of that joy as our partnership moves forward with Ballsfest .”],
  [With the rigorous treatment schedules these families juggle, along with the financial implications of treatment related costs, travel typically falls to the wayside. The financial resources are not available for travel, while the importance of vacations and memory making remain so critical. Through this newly developed partnership, Live Life Travel will be the exclusive travel partner for all Baller trips. Live Life Travel shares in the belief that family vacations can truly help lift the spirits of the children and families living with a diagnosis. “We are committed to creating customized travel experiences for all of our Baller families. We have also pledged to make a financial donation to Ballsfest for every family that travels with us. In addition, we will create a page/button on our website where our clients can also make contributions. We feel that this is just the beginning of what will be a very meaningful partnership,” shared Anne.],
  [Angie Silipigno, Executive Director of Ballsfest NY, shared, “Having been in the field of childhood cancer for a long time, I know that it takes more than medicine to heal these children. While working to cure the disease, it is so important to heal the heart and spirit as well. Partnering with Live Life Travel to create once-in-a-lifetimes experiences for our Ballers immediately felt like the perfect fit. Having the confidence in Anne’s heart and passion to put together special travel packages for each family means the world to us. It is our mission to really bring joy, hope, laughter, and everlasting moments to these amazing children and their families during an extremely difficult time.” After a Baller is presented with their personalized trip idea, this partnership will go into full effect to develop a perfectly laid plan to build on the patient’s interests and deliver an unforgettable experience.],
  [BALLSFEST is a registered nonprofit organization that lifts the spirits of young children, teens, and families affected by cancer. The term “Ballsfest” was created as a play on words by testicular cancer survivor, Frank DeBlasi, to reflect his positive spirit and outlook throughout his own battle. With his passion for children, Frank has focused on helping those battling remains positive and hopeful. BALLSFEST provides personalized gifts and experiences to Ballers at an annual signature event, as well as year-round programming and support to patients and families.],
  [Live Life Travel is your local Virtuoso travel advisor specializing in custom global experiences. From family vacations, multi-gen travel, honeymoons, special occasion, groups and luxury/family cruise, we have unparalleled access around the world. We offer personalized experiences, customized to make everyone’s trip extraordinary. By booking with a local trusted travel advisor, you will also always have peace of mind, which is the ultimate luxury. Live Life Travel was founded in 2015 by Anne Gordon who encourages everyone to live life to the fullest and appreciate every day. Anne also promotes taking all of your paid vacation time and to please travel with your children. \#livelifetravelnow www.livelifetravel.world],
  [The post Ballsfest and Live Life Travel partner appeared first on Live Life Travel .],
),
  insert-map: (:),
  word-count: 894,
  edited-for-length: false,
  debug-mode: false,
)

  #pull-quote([While working to cure the disease, it is so important to heal the heart and spirit as well.], [Anne Gordon])

}

{
  #standard-article(
  title: [4 Honeymoons and an Anniversary],
  author: [Anne Gordon],
  source-name: [Live Life Travel],
  images: (),
  paragraphs: (
  [class="p1"\> I t’s likely around the time when most of you are starting to think about your honeymoon. And while there is no right answer for everyone in terms of when to plan, we do have some general guidelines that we can share with you based on our professional experience:],
  [class="p1"\>The sweet spot to have your honeymoon planned is roughly 9 months before your wedding (the exception to this rule is that places such as the Amalfi Coast and The Greek Islands can be planned even earlier given the short season, high demand and limited availability).],
  [class="p1"\>If you are looking to book Sandals, they open their inventory 2 years before check-in date (vs. 1 year for most hotel inventory) and we recommend that you book as early as possible with your preferred agent as there are only benefits to doing so.],
  [class="p1"\>If you are not sure where you want to travel for your honeymoon yet, you are not alone. Eighty-five to ninety percent of the couples we meet say the same thing and this is something that we specialize in, so no reason to worry or stress. We really do take care of everything.],
  [class="p1"\>To help inspire all of you who are just starting to think about your honeymoon (or any other type of celebration travel), we would like to share with you ‘4 Honeymoons and a 20th Anniversary’ from 2019, along with their personal travel planning tips.],
  [Cape Town – 3 nights – Cape Point, Penguin Colony, Table Mountain],
  [Zambia – 3 nights – Victoria Falls, Elephant Café, Walking with Cheetahs, Sunset River Cruise, Private Dinner],
  [Kruger Park Safari – 4 nights – Mjejane River Lodge],
  [Johannesburg – 2 nights – Local Museums & Restaurants],
  [Even if you prefer to book your own travel, use a travel advisor for your honeymoon to make everything stress-free & super organized, as well as adding those special touches],
  [Be willing to try new things while you are in destination including experiencing the local culture and food],
  [Don’t be afraid to travel during the low season to take advantage of lower prices, more exclusive experiences and fewer crowds],
  [Bangkok – 2 nights – Floating Markets, Street Food Tour],
  [Chiang Mai – 3 nights – Elephant Sanctuary, Night Market Tour, Visit to Wat Phrathat Doi Suthep Temple],
  [Koh Samui – 6 nights – Big Buddha, Angthong National Marine Park],
  [Singapore – 1 day – Gardens by the Bay, Cloud Forest, Bumboat River Cruise],
  [Don’t be afraid to go big for your honeymoon; it’s a once in a lifetime experience, so make it count],
  [Don’t settle for the first travel advisor that you use if they are not for you; we tried several before we found Anne],
  [Always choose the “crazy” option – We opted for an extended layover in Singapore for the way home and ended up having an incredible experience that we would had completely missed if we had planned this on our own],
  [7 nights in an Over-The-Water Villa at The Rosewood Mayakoba],
  [Inclusive of an Adults-Only Beach Club with Pool and Taco Truck, Bicycles for the week, Private Plunge Pool and Hammock, Daily Breakfast and Private Boat Ride],
  [Choose a place that you love so much that you can return for anniversaries and other celebration travel including family travel],
  [Listen to the locals; We had the best tostadas of our entire life based on a recommendation of our driver in the village of El Publeto],
  [Be sure that your resort has a specified “Adults Only” section if it is a family resort; our favorite spot was the private beach club and adults only pool where the staff was impeccable],
  [2 nights – Vineyard on Mt. Etna – Private Mt. Etna Summit Jeep Experience, Private Cooking Class with Wine Tasting],
  [6 nights – Taormina – Evening Walking Tour with Culinary Experience, Pizza Making, Private Yacht Experience with Grotto Tours],
  [Whatever you do, DON’T skip your honeymoon],
  [Using a travel advisor is a MUST – All we had to do was show up and we were treated like celebrities the entire time, everything was perfect!],
  [Don’t overthink about anything, just enjoy it all. Sicily was perfect for us and even Andrew, who has never liked wine, acquired a taste for it there (we especially loved the Etna Rosso)],
  [3 nights – Rome – Colosseum Tour, Vatican with Sistine Chapel Tour],
  [1 night – Naples – Archeological Museum with Authentic Pizza Dinner],
  [3 nights – Sorrento – Private tour of Pompeii & Herculaneum, Lunch & Wine Tasting at Vineyard on Mt. Vesuvius, Lemon Farm Tour, Lunch & Shopping in Positano],
  [3 nights – Ravello – Anniversary Dinner at Belmond Hotel Caruso],
  [Having 24/7 in-destination contacts while traveling provided us with a peace of mind that we did not realize was available to us],
  [Go to Ravello on the Amalfi Coast; it was unbelievably beautiful, so laid back and relaxing and we felt so welcome there by the locals],
  [Make time to travel together for milestone anniversaries; It was the trip of a lifetime and we are so happy that we did it],
  [For more information on planning your next vacation, contact Anne Gordon at Live Life Travel. anne\@livelifetravel.world www.livelifetravel.world],
  [The post 4 Honeymoons and an Anniversary appeared first on Live Life Travel .],
),
  insert-map: (:),
  word-count: 1259,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Oven Roasted Potatoes],
  author: [Jess Rice],
  source-name: [Budget Bytes],
  images: (),
  paragraphs: (
  [There’s so much debate over which potatoes are best for mashing, roasting, or frying, and some potatoes are way more expensive than others! Let me simplify at least one recipe for you: Russet potatoes are always the cheapest where I shop, AND they yield the BEST crispy Oven Roasted Potatoes! What’s my secret? Par-boiling the potatoes first gives the outer layer so much texture, which makes them extra crispy when it comes time to roast them! I guarantee you will have no leftovers if you make this recipe (they’re that good!)],
  [I think everyone should have a solid roast potatoes recipe in their back pocket, and this one is mine. I start with a quick parboil, and like to salt the water well to season the potatoes from the inside out. Then I add baking soda to the water to help soften and break down the outside of the potatoes. Because it makes the water more alkaline (science!), the baking soda helps create a fluffier surface that adds even more texture to the parboiled potatoes. Those roughed up edges catch the oil, salt, garlic powder, and black pepper beautifully, so I get plenty of flavor and CRUNCH in every bite. It’s an easy, low-cost trick that plays its part in creating deeply golden, crisp roasted potatoes with soft and tender fully cooked centers!],
  [Dice the potatoes into 1 to 2-inch pieces. Cut the russets into similarly sized chunks so they roast and parboil evenly.],
  [Parboil until tender, not falling apart. You want the potatoes to be fork-tender, but still sturdy enough to hold their shape when tossed and roasted! The parboiling is just to partially cook them and soften the edges. They’ll finish cooking in the oven.],
  [Toss gently to add texture. After draining, toss the potatoes with the olive oil and seasonings just enough to create a more textured surface for browning. This is also one of my favorite ways to make a little oil go a long way. You only use what you need here, so there’s no waste!],
  [Spread them out in a single layer. I recommend giving the potatoes space on the baking sheet so they roast instead of steaming. Overcrowding is one of the quickest ways to lose the crisp finish.],
  [Roast at 425°F for the best color and texture. High heat helps make the crispest oven roasted potatoes. It also encourages the Maillard reaction (the browning process that gives roasted foods a golden color and deeper flavor!)],
  [Give them enough time to fully roast. At 425°F, roasted potatoes usually take about 40 minutes in the oven, with a flip halfway through, to get nicely browned and crisp. They’re ready when the edges look deeply golden and the outside feels crisp. Keep an eye on them just in case your oven runs a little hotter than mine!],
  [Print 
 Add to Collection Go to Collections],
  [class="wprm-recipe-instruction-text" style="margin-bottom: 5px;"\>Once the water returns to a boil, parboil the potatoes for 8 minutes and strain. They will be fork tender (but not falling apart completely) and very textured at this point which is perfect! This flakey outside part of the potato results in the very best crust when roasting.],
  [See how we calculate recipe costs here .],
  [class="wprm-recipe-notes"\> \*I like russet potatoes best for roasting because of the cost and how their low moisture, high starch content helps them crisp up in the oven. You can, of course, roast any potato you like with this method! Just note waxier varieties like Yukon Gold or red potatoes won’t usually get quite as crisp.],
  [\*\*Feel free to season these potatoes however you like. Add in smoked paprika , poultry seasoning , onion powder , dried herbs , or just use salt and pepper !],
  [class="wprm-nutrition-label-container wprm-nutrition-label-container-simple wprm-block-text-normal" style="text-align: left;"\> Serving: 1 serving | Calories: 274 kcal | Carbohydrates: 41 g | Protein: 5 g | Fat: 11 g | Sodium: 2498 mg | Fiber: 3 g],
  [Gather all of your ingredients and preheat the oven to 425°F.],
  [Prep the potatoes: Peel the 2 pounds russet potatoes, then cut them into large 1 to 2-inch chunks.],
  [Heat the water: In a large pot, bring 2 quarts water (8 cups) and 1 Tbsp salt to a rolling boil.],
  [Prep the parsley: While the water heats, mince ½ Tbsp fresh parsley and set it aside.],
  [Parboil the potatoes : Once boiling, add the diced potatoes along with ½ tsp baking soda. Let the water come back up to a boil.],
  [When the water returns to a boil, parboil the potatoes for 8 minutes. Drain well. The potatoes should be fork-tender but not falling apart, and the outsides should look textured and flaky, which helps create a crispier roasted finish.],
  [Season the potatoes: Transfer the drained potatoes to a large bowl and gently toss them with 3 Tbsp olive oil, ½ tsp salt, ¼ tsp ground black pepper, and ½ tsp garlic powder.],
  [Roast potatoes in the oven: Spread the seasoned potatoes out on a parchment-lined baking sheet in an even layer. Roast the potatoes for 20 minutes.],
  [After 20 minutes, flip all of the potatoes and bake for an additional 20 minutes. This is an important step to ensure even browning and a crispy crust all the way around!],
  [Remove the potatoes from the oven.],
  [Season and serve: Finish with the remaining ½ tsp salt and the minced parsley before serving. Enjoy!],
  [These easy oven roasted potatoes go with just about everything! Serve them with baked ham during the holidays, roasted chicken for an easy family dinner, or my lentil loaf for a hearty meat-free option. Add a few of your favorite sides, and you’ve got an easy and well rounded meal. The leftovers are also delicious chopped up and added to the filling for a veggie pot pie !],
  [I prefer these roasted potatoes when served fresh, but leftovers will keep in an airtight container in the fridge for 3-4 days. Reheat them in a 375°F oven or air fryer until heated through and crisp again.],
  [They can also be frozen for up to 3 months, but the texture of the potatoes may change after freezing and reheating. If you want to freeze this recipe, it’s best to parboil the potatoes, coat them in the oil and seasonings, then flash freeze them on a baking sheet. Once solid, transfer them to a freezer-safe container and then roast from frozen.],
  [Smoky Roasted Breakfast Potatoes are a hands-off, budget-friendly side with crispy edges, tender middles, and just enough smoky paprika flavor to make breakfast feel a little more special.],
  [These Parmesan Roasted Potatoes are golden, crisp, and seriously hard to stop snacking on!],
  [I’d make these Salt & Vinegar Potatoes anytime I want a potato side that feels a little different.],
  [Rosemary Roasted Potatoes are an easy, flexible side that go with just about anything, and the garlic and rosemary make them taste classic in the best possible way.],
  [\$3.45 recipe \/ \$0.86 serving],
  [\$3.34 recipe \/ \$0.84 serving],
  [\$5.67 recipe \/ \$0.47 serving],
  [\$3.17 recipe \/ \$0.79 serving],
  [The post Oven Roasted Potatoes appeared first on Budget Bytes .],
),
  insert-map: (:),
  word-count: 1683,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Should you pay your rent or mortgage with Bilt? We crunch the numbers],
  author: [Katie Genter and Emily Thompson],
  source-name: [The Points Guy],
  images: (),
  paragraphs: (
  [One of the biggest monthly expenses for many consumers is their rent or mortgage payment. Some landlords and mortgage providers may accept credit card payments. But, since Bilt Rewards offers a fee-free way to pay most rent and mortgage payments and earn Bilt Points on your payments, it's worth considering.],
  [Not a member? Join Bilt Rewards now to start earning and redeeming Bilt points.],
  [Bilt points are a valuable currency based on TPG's February 2026 valuations . So here's what you need to know about earning Bilt points on rent and mortgage payments, including whether it's a good idea to do so.],
  [You can earn Bilt points on rent and mortgage payments even if you don't have a Bilt card.],
  [Specifically, if you pay rent through Bilt with a non-Bilt Visa, Mastercard, American Express or Discover credit card, you'll usually earn 1 point per \$2 spent (excluding rent payment fees).],
  [However, if you pay your rent through Bilt using an eligible Atmos Rewards card , you'll earn 3 Atmos Rewards points per dollar spent on each rent payment (on up to \$50,000 per year). And if you pay your rent through Bilt using an eligible United MileagePlus card , you'll earn 2 United Airlines miles per dollar spent on each rent payment (on up to \$50,000 per year).],
  [If you pay rent through Bilt with a debit card or any other type of credit card, you'll earn 250 points per monthly rent payment.],
  [JOHNNYGREIG/GETTY IMAGES],
  [Meanwhile, if you pay your mortgage through Bilt without using a Bilt card, you'll earn 100 points per contractual mortgage payment made via automated clearing house transfer, 250 points per payment made with a debit card and 1 point per \$2 spent per payment with a non-Bilt Mastercard (excluding mortgage payment fees).],
  [Non-Bilt cards incur a 3% processing fee, though, while debit card payments incur a flat \$9.95 fee.],
  [Related: New Bilt 2.0 cards have arrived: How you can earn points on rent, mortgages and more],
  [Luckily, you can earn more points on housing payments and avoid fees by using a Bilt card.],
  [If you have the Bilt Blue Card (see rates and fees ), Bilt Obsidian Card (see rates and fees ) or Bilt Palladium Card (see rates and fees ), you'll earn Bilt points on nonhousing purchases with your card.],
  [BILT],
  [But cardholders also earn bonus rewards, and these rewards can let you earn Bilt points on housing payments without any transaction fees. The bonus rewards are Bilt Cash or housing-only rewards, and you must choose one of these when you activate your card. However, you can switch your bonus rewards choice each month.],
  [Here's a look at each option, including how each lets you earn Bilt points on housing payments. Regardless of your choice, keep in mind that your rent or mortgage payment will not be applied to your Bilt card's credit line. Instead, Bilt will automatically debit the rent or mortgage charges from your bank account via an automated clearing house transfer.],
  [The Bilt Cash pathway to earning Bilt points on housing payments],
  [If you opt for the Bilt Cash pathway to earning Bilt points on housing payments, you'll earn 4% back in Bilt Cash on all nonhousing purchases with your Bilt card. You can then redeem Bilt cash for various rewards, including unlocking Bilt points on housing payments. You can redeem Bilt Cash at a rate of 3 cents per point to unlock up to 1 point per dollar spent on Bilt housing payments each month.],
  [So, if your monthly housing payment is \$1,000, you could redeem up to \$30 of Bilt Cash per month to unlock up to 1,000 Bilt points per month. You'd need to spend \$750 on nonhousing purchases with your Bilt Card to earn \$30 of Bilt Cash.],
  [Related: Everything you need to know to set up your Bilt card for paying rent],
  [The housing-only rewards pathway to earning Bilt points on housing payments],
  [If you opt for the housing-only rewards pathway to earning Bilt points on housing payments, you won't earn Bilt Cash on nonhousing purchases with your Bilt card. However, you will automatically earn Bilt points on Bilt housing payments with no transaction fee.],
  [The rate at which you earn points on Bilt housing payments is based on your everyday spending as a percentage of your monthly rent or mortgage, as follows:],
  [Less than 25%: 250 Bilt points per billing cycle],
  [At least 25%, but less than 50%: 0.5 points per dollar spent on Bilt housing payments],
  [At least 50%, but less than 75%: 0.75 points per dollar spent on Bilt housing payments],
  [At least 75%, but less than 100%: 1 point per dollar spent on Bilt housing payments],
  [At least 100%: 1.25 points per dollar spent on Bilt housing payments],
  [So, if your monthly housing payment is \$1,000, you'd need to spend at least \$1,000 per month in nonhousing expenses on your Bilt card to earn 1.25 points per dollar spent on your Bilt housing payment (which would be 1,250 points). Meanwhile, if you spent at least \$750 but less than \$1,000 per month, you'd earn 1 point per dollar spent on your Bilt housing payment (1,000 points). Of course, the amount you'd need to spend on nonhousing expenses changes depending on your monthly housing payment.],
  [Related: I earned points paying my mortgage via Bilt — how to set up your account to do the same],
  [The calculation of whether to choose Bilt Cash or housing-only rewards is based on your monthly housing payment, how you'll redeem Bilt Cash and how much you spend on nonhousing purchases with your Bilt card.],
  [I highly recommend using our Bilt Calculator to see what's best for you. But, if you prefer, you can also check out the following scenarios to see how the math plays out. In each scenario, we focus on monthly nonhousing spending amounts around the thresholds for housing-only rewards, as this is where you can see the biggest differences.],
  [Monthly housing payment of \$500],
  [Assuming you have a monthly housing payment of \$500, here's how the math would work out for both Bilt Cash and housing-only rewards.],
  [Monthly nonhousing spending on your Bilt card Bilt Cash earned on nonhousing spending Value of points unlocked on housing payments based on TPG's Feb. 2026 valuations plus remaining Bilt Cash Points earned on \$500 monthly housing payment as housing-only rewards Value of points earned as housing-only rewards based on TPG's Feb. 2026 valuations \$0 \$0 \$0 250 points \$5.50 \$125 \$5, which could be redeemed to unlock 166 Bilt points on housing payments per month \$3.65 250 points \$5.50 \$250 \$10, which could be redeemed to unlock 333 Bilt points on housing payments per month \$7.33 375 points \$8.25 \$375 \$15, which could be redeemed to unlock 500 Bilt points on housing payments per month \$11 500 points \$11 \$500 \$20, \$15 of which could be redeemed to unlock 500 Bilt points on housing payments per month \$16 625 points \$13.75 \$1,000 \$40, \$15 of which could be redeemed to unlock 500 Bilt points on housing payments per month \$36 625 points \$13.75],
  [Monthly housing payment of \$1,000],
  [Assuming you have a monthly housing payment of \$1,000, here's how the math would work out for both Bilt Cash and housing-only rewards.],
  [Monthly nonhousing spending on your Bilt card Bilt Cash earned on nonhousing spending Value of points unlocked on housing payments based on TPG's Feb. 2026 valuations plus remaining Bilt Cash Points earned on \$1,000 monthly housing payment as housing-only rewards Value of points earned as housing-only rewards based on TPG's Feb. 2026 valuations \$0 \$0 \$0 250 points \$5.50 \$250 \$10, which could be redeemed to unlock 333 Bilt points on housing payments per month \$7.33 500 points \$11 \$500 \$20, which could be redeemed to unlock 666 Bilt points on housing payments per month \$14.65 750 points \$16.50 \$750 \$30, which could be redeemed to unlock 1,000 Bilt points on housing payments per month \$22 1,000 points \$22 \$1,000 \$40, \$30 of which could be redeemed to unlock 1,000 Bilt points on housing payments per month \$32 1,250 points \$27.50 \$1,500 \$60, \$30 of which could be redeemed to unlock 1,000 Bilt points on housing payments per month \$52 1,250 points \$27.50],
  [Monthly housing payment of \$2,000],
  [Assuming you have a monthly housing payment of \$2,000, here's how the math would work out for both Bilt Cash and housing-only rewards.],
  [Monthly nonhousing spending on your Bilt card Bilt Cash earned on nonhousing spending Value of points unlocked on housing payments based on TPG's Feb. 2026 valuations plus remaining Bilt Cash Points earned on \$2,000 monthly housing payment as housing-only rewards Value of points earned as housing-only rewards based on TPG's Feb. 2026 valuations \$0 \$0 \$0 250 points \$5.50 \$500 \$20, which could be redeemed to unlock 666 Bilt points on housing payments per month \$14.65 1,000 points \$22 \$1,000 \$40, which could be redeemed to unlock 1,333 Bilt points on housing payments per month \$29.33 1,500 points \$33 \$1,500 \$60, which could be redeemed to unlock 2,000 Bilt points on housing payments per month \$44 2,000 points \$44 \$2,000 \$80, \$60 of which could be redeemed to unlock 2,000 Bilt points on housing payments per month \$64 2,500 points \$55 \$3,000 \$120, \$60 of which could be redeemed to unlock 2,000 Bilt points on housing payments per month \$104 2,500 points \$55],
  [Monthly housing payment of \$4,000],
  [Assuming you have a monthly housing payment of \$4,000, here's how the math would work out for both Bilt Cash and housing-only rewards.],
  [Monthly nonhousing spending on your Bilt card Bilt Cash earned on nonhousing spending Value of points unlocked on housing payments based on TPG's Feb. 2026 valuations plus remaining Bilt Cash Points earned on \$4,000 monthly housing payment as housing-only rewards Value of points earned as housing-only rewards based on TPG's Feb. 2026 valuations \$0 \$0 \$0 250 points \$5.50 \$1,000 \$40, which could be redeemed to unlock 1,333 Bilt points on housing payments per month \$29.33 2,000 points \$44 \$2,000 \$80, which could be redeemed to unlock 2,666 Bilt points on housing payments per month \$58.65 3,000 points \$66 \$3,000 \$120, which could be redeemed to unlock  4,000 Bilt points on housing payments per month \$88 4,000 points \$88 \$4,000 \$160, \$120 of which could be redeemed to unlock 4,000 Bilt points on housing payments per month \$128 5,000 points \$110 \$6,000 \$240, \$120 of which could be redeemed to unlock 4,000 Bilt points on housing payments per month \$208 5,000 points \$110],
  [Choose housing-only rewards for the 250 Bilt points per billing cycle if you plan to spend less than \$137.50 (\$187.50 if you'd redeem points to unlock Bilt points on housing payments) on nonhousing purchases with your Bilt card each month.],
  [It's often better to select housing-only rewards if you'll aim your monthly nonhousing spending on your Bilt card to barely surpass the 25% or 50% thresholds for the ratio of nonhousing spending to housing spending.],
  [Once you surpass the 50% threshold for the ratio of nonhousing spending to housing spending, you'll usually be better off earning Bilt Cash.],
  [Keep in mind that the calculation also depends on whether you'll redeem Bilt Cash to unlock points on housing payments. After all, while TPG's February 2026 valuations peg the value of Bilt points at 2.2 cents each, you can only unlock Bilt points on housing payments by redeeming Bilt Cash at a rate of 3 cents per point.],
  [Related: How good are Bilt's first-ever welcome offers? Earn up to 50,000 points],
  [If you have monthly rent or mortgage payments, it may make sense to get a Bilt card and use it to pay your rent or mortgage. After all, you don't have to pay transaction fees on housing payments when you have one of the three Bilt cards and you let Bilt debit the rent or mortgage charges from your bank account via an automated clearing house transfer. Plus, you can earn Bilt points on your housing payments.],
  [Alternatively, if you have an eligible Atmos Rewards card, you may want to use it when paying rent through Bilt as you'll earn 3 Atmos Rewards points per dollar spent on each rent payment (on up to \$50,000 per year). You'll have to pay a 3% transaction fee, but this fee may be worth paying if you get good value when redeeming Atmos Rewards points.],
  [In short, consider your other options for paying your rent or mortgage and assess how much value you'll get from each pathway in the Bilt Rewards program. Especially considering that the no-annual-fee Bilt Blue Card (see rates and fees ) unlocks the ability to pay rent or mortgages through Bilt with no transaction fees, it may be your best path toward earning rewards on housing payments.],
  [Related reading:],
  [Bilt Blue Card review: No-annual-fee rewards on rent or mortgage],
  [Bilt Obsidian Card review: Earn valuable points in popular bonus categories],
  [Bilt Palladium Card review: High earnings for Bilt-focused travelers],
  [Editorial disclaimer: Opinions expressed here are the author’s alone, not those of any bank, credit card issuer, airline or hotel chain, and have not been reviewed, approved or otherwise endorsed by any of these entities.],
),
  insert-map: (:),
  word-count: 2246,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Red Gomashio],
  author: [Heidi Swanson],
  source-name: [101 Cookbooks],
  images: (),
  paragraphs: (
  [Gomashio is a simple Japanese seasoning made from toasted sesame seeds and salt. It adds crunch, nuttiness, and added nutrients from the sesame seeds. A few years ago I started making a red version and it quickly became a kitchen staple. Dense with sesame, dynamic with chile powder and smoked paprika, the wildcard ingredient is green cardamom. Fragrant cardamom seeds are ground with mortar and pestle along with some of the sesame and the resulting blend of spices really sings – especially when it hits something hot. And while not at all traditional, you can use it in many of the same ways you might use a more traditional version of goma (sesame) shio (salt).],
  [class="p1"\> Cardamom : Your cardamom seeds should be fragrant when crushed. You can buy cardamom in different forms – whole cardamom pods, cardamom seeds, ground cardamom seeds. For this recipe you want to start with pods or whole seeds. If you buy the seeds, it’s a bit of a shortcut and you can simply pounds them in a mortar and pestle, or grind them in a clean pepper grinder. If you start with seeds you’ll need about 1/4 teaspoon for this recipe.
 
My friend Wendy gifted me a few beautiful glass jars of spices last week (her calligraphy!), and looking at the cardamom I took it as a sign to make a fresh round of red gomashio.],
  [class="p1"\> Sesame Seeds : I typically keep unhulled sesame seeds on hand, and that’s what I use here. Fresher is better. You want to keep sesame seeds in an airtight container, out of direct light, preferably refrigerated if you don’t go through them quickly.],
  [class="p1"\> Onion : I prefer to use dried onion flakes here, but they can be tricky to find. Onion powder does the job as well, and is available in most stores. That said, if you plan ahead, one of my favorite ingredient discoveries lately is the toasted onion powder from Burlap & Barrel (not sponsored, just a fan). It’s good in place of the dried onion flakes here.],
  [class="p1"\> Salt : I like to use flaky sea salt here, you can kind of crush it with your fingers into small, irregular shapes that are nice. Alternately, pink Himalayan sea salt pounded a bit with a mortar and pestle is a nice alternative.],
  [class="p1"\> Chile powder : I like to use Kashmiri chile powder here. It has a vibrant spiciness, fruity notes, and for the electric color (!) it brings. If you want to use another chile powder, add it gradually as your final ingredient, adding more until the overall blend is to your liking.],
  [class="p1"\>This is a wildly adaptable seasoning. I love it sprinkled over labneh and drizzled with a finishing extra virgin olive oil. It’s good sprinkled over homemade pasta tossed with a generous amount of butter or olive oil, some Parmesan, and whatever fresh herbs you have on hand. It’s A-plus on a baked potato (or mashed potatoes omg). Or sprinkled across a plate of hard-boiled eggs . Basically it’s an easy way to make everyday staples a bit special. You see it sprinkled above on onigirazu, it’s equally at home on rice bowls, onigiri, and soba bowls. I also love to sprinkle it all over guacamole before serving. I could go on and on, basically keep it on your counter and use it constantly.],
  [Here are a few process shots and visual cues in case you need them.],
  [Grind the cardamom : This is the texture you’re after when grinding the cardamom seeds. A bit of texture along with a fine grind. It’s the grind I go for when grinding black pepper.],
  [Grind some of the sesame seeds : If you have a suribachi , this would be the time to use it – I bought this one by Colleen Hennessey for Permanent Collection years ago and it’s one of my prized kitchen possessions. But a mortar and pestle works nicely as well (pictured). Then you add the rest of ingredients.],
  [Add the rest of the toasted sesame seeds : Stir in the rest of the seeds and then adjust the seasoning to your linking with more chile powder, brown sugar, salt, etc. Keep it on your counter and sprinkle with enthusiasm!],
  [Continue reading Red Gomashio on 101 Cookbooks],
),
  insert-map: (:),
  word-count: 756,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Smoked Labneh],
  author: [Heidi Swanson],
  source-name: [101 Cookbooks],
  images: (),
  paragraphs: (
  [If you have a stovetop smoker, or a smoker donabe (ibushi gin), smoked labneh should be high on your list of things to make. Labneh is made simply by straining yogurt. The resulting consistency is rich, creamy and beautiful. Amazing on its own, you can also incorporate herbs, spices, or other ingredients. I know the number of you with a stovetop smoker is probably slim, but I love experimenting with mine, always trying to come up with more ways to use it, especially now that we have a gas range again. A long way of saying, if you want to play around with your smoker more, I see you. I use mine for all sorts of things – nuts, cheeses, tofu, vegetables, and on and on. So I’ll try to post more as I’m using it.],
  [class="p1"\>Smoked labneh has been on my list of things to make for some time now. Late last year we made a few trips to San Francisco to make sure we were ready to make the move back from LA. I would walk through the Presidio to lunch at Dalida , in part, because I love their homemade pita situation – called Breaking Bread. The pita comes with a trio of spreads (hummus, muhammara, smoked yogurt), some pickles and olives. The smoked yogurt is a show-stopper – rich, creamy, luxe. The server wasn’t sure how it was prepared but I started thinking about how to approach it once I could get my smoker unpacked. I already make homemade labneh regularly, so it wouldn’t be too much of a jump. Flash forward, and I’ve made smoked labneh a number of times in the weeks since!],
  [class="p1"\>I’ve been using a cold-smoke technique and it works nicely. It’s where you keep the yogurt cold but flood the area around it with smoke. Every smoker is slightly different, so you might need to tweak your approach, but this will give you the general idea of how to think about it. You can see in my diagram below how things are layered in the smoker. Starting at the bottom: a piece of foil, wood chips, the grate, a bowl of ice and some water, the shallow container of labneh, the lid eventually goes on above that.],
  [You can see the aluminum foil sitting on the bottom of the smoker topped with wood chips. The foil makes for easy cleanup.],
  [Below, a stainless steel bowl of ice and some water sits on top of a grate, which keeps the bowl from having direct contact with heat or the wood chips. The labneh sits in the ice, keeping the yogurt cool through the smoking process.],
  [Alternate approach: There’s also a method for smoking Labneh in the NOPI cookbook , but I haven’t attempted it yet. The labneh is formed into a puck shape and placed on a piece of parchment paper inside the smoker – no ice. They also use different aromatics for smoking (oolong tea, caraway seeds, pink peppercorn, etc). I suspect the biggest difference would be texturally, with the parchment version losing more moisture and possibly taking on more flavor because more surface area is exposed? Excited to take this version for a spin as well.],
  [class="p1"\>Every smoker has its own quirks and personalities. My advice here is to take good notes. You want a nice, round, balance of smoky notes. Aim for the sweet spot between too subtle and too strong acrid (yikes). Every time I use the smoker I make note of: what I’m smoking, what type of wood chips \/ herbs, etc., and how long. Then note how I would increase or decrease the time in the future. Good notes are key to getting a good working relationship with your smoker. Twenty minutes seems to be the sweet spot here for the labneh using applewood chips. A similar timeframe worked well for this smoked chocolate mousse .],
  [class="p1"\>Here’s what my smoker looks like, I loooove it (not sponsored). If I didn’t have my Ibushi Gin (donabe smoker) another way to get smoky flavor into the labneh might be to use a smoked salt. I’d grind it finely with a mortar and pestle and go from there. I’ve never really liked liquid smoke, so that wouldn’t be my move, but that doesn’t mean you couldn’t experiment a bit as yet another approach. There could very well be better liquid smokes on the market compared to the last time I played around with it.],
  [Drizzled with olive oil and sprinkled with red gomashio (pictured above), along with candied nuts with rose water, seeded flatbread, and assorted cookies.],
  [In place of the poblano yogurt in this mushroom tartine .],
  [In place of the ricotta on this roasted mushroom sandwich .],
  [In place of the green chile yogurt in this sourdough galette .],
  [Rolled into 1-inch balls, rolled in spices, herbs, and/or seeds, and kept, refrigerated, in a jar topped off with olive oil.],
  [More Ways to Use Stovetop Smoker],
  [Continue reading Smoked Labneh on 101 Cookbooks],
),
  insert-map: (:),
  word-count: 895,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [UPDATE: TSA to pay officers 'immediately' as airport security lines mount],
  author: [Sean Cudahy],
  source-name: [The Points Guy],
  images: (),
  paragraphs: (
  [The Transportation Security Administration has "immediately" begun the process of paying workers, the Trump administration said Friday afternoon — and TSA officers could see paychecks in their bank accounts as soon as Monday.],
  [The move came as lawmakers on Capitol Hill remained deadlocked on legislation to fully reopen the government, and as travelers continued to face major backups at airport security checkpoints.],
  [TSA workers missed another paycheck on Friday as the shutdown of the U. S. Department of Homeland Security approached the six-week mark.],
  [Officer call-outs have surged in recent weeks, leading to the highest wait times in the TSA's nearly 25-year history, the agency's top leader told Congress this week.],
  [At Houston's George Bush Intercontinental Airport (IAH), the de facto epicenter of the recent travel chaos, backups stretched up to three and a half hours Friday.],
  [Elsewhere, Baltimore/Washington International Thurgood Marshall Airport (BWI) advised passengers to arrive at the terminal three hours before departure amid the spring break rush.],
  [There had been momentum on Capitol Hill toward ending the partial government shutdown, which began on Feb. 14.],
  [Early Friday, the U. S. Senate broke a weekslong stalemate and voted to fund most of the DHS, including the TSA. But the measure appeared to face an uphill climb in the House.],
  [President Donald Trump on Friday afternoon said he had ordered DHS to "immediately pay" workers, saying air travel had reached a "breaking point."],
  [Airlines and leaders across the travel sector had praised the move when Trump first announced the plans Thursday evening.],
  [A security line reaches outside the terminal this week at Hartsfield-Jackson Atlanta International Airport (ATL). MEGAN VARNER/GETTY IMAGES],
  [In a statement to TPG Friday afternoon, a DHS spokesperson confirmed the department had already begun the process of paying its workforce.],
  [Still uncertain, though, is how quickly airport security checkpoints could return to normal wait times.],
  [One reason for optimism: After last fall's larger federal shutdown finally ended after 43 days, call-outs among air traffic controllers immediately lessened — and flight operations rapidly improved.],
  [Will TSA operations snap back to normal in the same way?],
  [Travelers, airlines and lawmakers alike can hope. However, it's important to keep in mind that TSA officers have now endured not one — but two — 40-plus-day shutdowns since October, going without paychecks during both stretches.],
  [So it's certainly possible it could take some time for TSA checkpoint operations to return fully to pre-shutdown wait times.],
  [Travelers wait in a security line at Hartsfield-Jackson Atlanta International Airport (ATL). MEGAN VARNER/GETTY IMAGES],
  [For now, if you're headed to the airport this weekend — especially Friday or Sunday — I'd continue to prepare for longer lines than normal. Here's a rundown of my top tips for getting through security during this unpredictable stretch .],
  [Airlines issue travel waivers],
  [As of late Thursday night, Delta Air Lines had flexible travel waivers in place for customers at ATL and New York's John F. Kennedy International Airport (JFK). United Airlines had done the same for its IAH hub .],
  [And, as TPG reported earlier this week, budget carrier Allegiant Air had granted customers significant flexibility to change their tickets during the shutdown.],
  [TSA app remains unreliable],
  [Also, keep in mind that the TSA's app, which typically shows live checkpoint wait times, will likely remain unreliable, since it's not updated regularly during a federal shutdown.],
  [Your best bet before heading to the airport: Continue checking your airport's website and social media feeds to see whether it offers a wait-time tracker of its own.],
  [Even beyond this federal shutdown — which, by the way, still technically isn't over — longer-term concerns remain at airports. Already, some 480 TSA officers have left their jobs since this latest partial federal shutdown began, acting TSA Administrator Ha Nguyen McNeill testified this week on Capitol Hill.],
  [And considering it takes months to train new hires, she noted this could pose a major problem ahead of one of the century's biggest sporting events in the U. S. this summer.],
  ["This is a dire situation," McNeill said. "We are facing a potential perfect storm of severe staffing shortages and an influx of millions of passengers at our airports for the World Cup games in less than 80 days."],
  [This is a developing story. Check back for further updates.],
  [Related reading:],
  [When is the best time to book flights for the cheapest airfare?],
  [The best airline credit cards],
  [What exactly are airline miles, anyway?],
  [6 real-life strategies you can use when your flight is canceled or delayed],
  [Maximize your airfare: The best credit cards for booking flights],
  [The best credit cards to reach elite status],
  [What are points and miles worth? TPG's monthly valuations],
  [Editorial disclaimer: Opinions expressed here are the author’s alone, not those of any bank, credit card issuer, airline or hotel chain, and have not been reviewed, approved or otherwise endorsed by any of these entities.],
),
  insert-map: (:),
  word-count: 819,
  edited-for-length: false,
  debug-mode: false,
)

}

#article-row((
  [
    standard-article(
  title: [Crispy Chickpeas],
  author: [Heidi Swanson],
  source-name: [101 Cookbooks],
  images: (),
  paragraphs: (
  [I’m posting this crispy chickpea recipe because I use them a lot (like in this asparagus ribbon salad ), and there are a number of tricks you need to deploy to get them deluxe crunchy.],
  [Crispy Chickpeas: Pro Tips],
  [Sad, chewy chickpeas are not what you’re after here. And there are a number of things you can do to get golden, super-crisp chickpeas.],
  [Dry well : Get your chickpeas extra dry before baking, and you’ve won half the battle. – Hot oven: Crank that oven up, get it screaming hot.],
  [Hot pan : Preheat your baking sheet. Chickpeas coated in oil hitting a hot pan is the pairing you’re after, and the hot pan gets things crisping more quickly.],
  [Don’t overcrowd : If you cram your chickpeas onto a small pan they’ll steam. The opposite of what you want for crispiness.],
  [Ways To Use Crispy Chickpeas],
  [In salads : Swap in some crispy chickpeas for the regular chickpeas in this quinoa salad , toss some into this favorite coleslaw , or add some to this wedge salad . If none of those strike the right note, browse the salad recipes – lots of salads there that would welcome some crispy chickpeas. Use them in place of croutons.],
  [Lunch on the go : I love including crispy chickpeas in bento-style, feel-good lunches .],
  [all chickpea recipes],
  [Continue reading Crispy Chickpeas on 101 Cookbooks],
),
  insert-map: (:),
  word-count: 259,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [∞ The Dalrymple Report: Ring, Olympics, Siri slips again],
  author: [Jim Dalrymple],
  source-name: [The Loop],
  images: (),
  paragraphs: (
  [Ring had an amazing ad during the Super Bowl that will use its camera network to help find lost dogs. Sounds great, but Dave has a warning about the new service. The Olympics started and Dave and I have been watching all kinds of different sports. It looks like some of the best features of Siri have once again slipped and will not be introduced when Apple said they would.],
  [Follow this podcast],
  [Brought to you by :],
  [CleanMyMac : Get Tidy Today! Try 7 days free and use my code DALRYMPLE for 20% off at clnmy.com/DALRYMPLE],
  [Show Notes:],
  [Super Bowl ad for Ring’s dog-tracking cameras stirs privacy controversy],
  [The medal count],
  [F. A. A. Halts All Flights at El Paso Airport for 10 Days],
  [Update Your Apple Home App Immediately to Avoid Issues],
  [Gurman: New Apple products],
  [Gurman: Siri delayed again],
  [Why You Shouldn’t Buy the Next MacBook Pro],
  [AirPods cameras],
  [Shows and movies we’re watching],
  [Quicksand, Netflix],
  [Shrinking, Apple TV],
  [Wonder man, Disney+],
),
  insert-map: (:),
  word-count: 163,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    brief-group((
      [#brief-item([KC Morgan], source-name: [Inhabitat], [Among the oldest tools that human hands ever created are axes, used to chop wood for fires and buildings. Wood is truly the mother of sustainable resources, a material that will grow back again and again. And now, wood is becoming the "it" design material. Sweden is starting an ambitious new project that will demonstrate the majesty of wood, and the possibilities it represents in sustainable building.])],
      [#brief-item([Sujata Gupta], source-name: [Science News], [Instagram and YouTube intentionally designed social media platforms to hook users, a landmark court case found. A pediatrician explains the ruling’s impact.])],
      [#brief-item([Bonface Landi], source-name: [Inhabitat], [Outwardly, gardens look like sustainable spaces that help absorb excess carbon from the atmosphere. While this might be true, not all gardens help reduce atmospheric carbon dioxide. Some gardens contribute to carbon pollution. Unfortunately, most gardeners are not even aware that their gardens are a source of carbon and other greenhouse gas pollutants. Even so, it is possible to attain a net-zero garden and in some cases, create a carbon sink in your garden.])],
      [#brief-item([Jake Buehler], source-name: [Science News], [Fossil jaw remains found in Egypt suggest that the earliest modern apes evolved in North Africa, not in East Africa where most fossils have been found.])],
    ))
  ],
), ruled-indices: (1, 2,))

#article-row((
  [
    standard-article(
  title: [∞ The Dalrymple Report: Refurbished gear, Apple execs, and 3D printing],
  author: [Jim Dalrymple],
  source-name: [The Loop],
  images: (),
  paragraphs: (
  [With the holidays coming up, Dave and I talk about buying refurbished Apple products and whether or not we woould do it. There has been a shake up at Apple with a couple of executives choosing to retire early next year. We have talked before about how great Apple hardware is, but 3D printing Apple Watches and the process they use takes everything to the next level.],
  [Follow this podcast],
  [Brought to you by :],
  [CleanMyMac : Get Tidy Today! Try 7 days free and use my code DALRYMPLE for 20% off at clnmy.com/DALRYMPLE],
  [Show Notes:],
  [Buying Apple for Xmas? Consider refurbished],
  [Apple announces executive transitions],
  [Alan Dye Was in Tim Cook’s Blind Spot],
  [Apple’s Johny Srouji],
  [3D printing Apple Watch and why it’s a big deal],
  [Shows and movies we’re watching],
  [The Secret of Crickley Hall, Hulu],
  [Netflix to Acquire Warner Bros],
  [Hugh Laurie (House, The Night Manager, Chance) joins Apple TV’s “Tehran”],
),
  insert-map: (:),
  word-count: 154,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [2026 Easter Recipe Guide! 50 Of the Best Easter Recipes!],
  author: [Jessica],
  source-name: [How Sweet Eats],
  images: (),
  paragraphs: (
  [Today I’m sharing the best of the best easter recipes with 50 of my favorite dishes for the holiday. Appetizers and snacks, brunch and dinner, finished off with cocktails and dessert!],
  [Time to put together a fabulous menu for the holiday!],
  [And I still have a lot of great Easter recipes coming to you in the next few weeks, but in the meantime, figured you could get the ball rolling with your menu.],
  [The dishes at Easter are not my favorite – I’m not a huge fan of ham. So because of that, over the years I’ve come up with tons of delish plates that I DO love at Easter. Whether it’s brunch, dinner, dessert- I’ve got you covered!],
  [P. S. While you’re at it, you can dye eggs with cool whip and they will look like tie dye unicorn eggs. Fun!],
  [Are you an Easter brunch or dinner person? I’m kind of… both. And chocolate peanut butter eggs, always.],
  [50 of the Best Easter Recipes],
  [(more…)],
  [The post 2026 Easter Recipe Guide! 50 Of the Best Easter Recipes! appeared first on How Sweet Eats .],
),
  insert-map: (:),
  word-count: 185,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#colophon([Quiet Tribune], [Vol. 1, No. 010], [2026-03-30])
