// Generated by OffScroll Typst renderer
// Edition: Informed Register — 2026-03-30

#import "templates.typ": *

#set page("us-letter",
  margin: 0.5in,
  footer: context {
    if here().page() > 1 {
      set text(7pt, font: "Source Sans 3", fill: luma(153))
      line(length: 100%, stroke: 0.5pt + luma(204))
      v(0.05in)
      align(center)[Informed Register \u{2014} 2026-03-30]
    }
  }
)

#set text(10pt, font: "Source Serif 4", fill: luma(26), hyphenate: true)
#set par(justify: true, leading: 0.52em)

#masthead([Informed Register], [Vol. 1, No. 019], [2026-03-30]
)

// --- Front Page Feature ---
#feature-article(
  title: [Actor Taye Diggs on How Losing His Parents to Cancer Changed His Life],
  kicker: [Cover Story],
  author: [Healthline],
  source-name: [Healthline],
  deck: [Actor Taye Diggs lost both his parents to cancer and shares how this experience has shaped his life since.],
  lead-text: "Photo by James Willis",
  lead-first-alpha: 0,
  body-paragraphs: (
  [Actor Taye Diggs has opened up about losing both his parents to cancer.],
  [He is advocating for early cancer detection and encouraging others to take charge of their health.],
  [Diggs discusses how his experience with his parents has affected his approach to health and fatherhood.],
  [Actor Taye Diggs is best-known for his roles on TV shows like “All American” and “Private Practice,” and films like “Rent” and “The Best Man.”],
  [Now, he’s talking about his personal experience with cancer and how early detection can make all the difference.],
  [“It’s kind of positive and negative … positive in that I want to make people aware, negative in that I have a personal connection to cancer,” Diggs told Healthline.],
  [Diggs is raising cancer awareness and encouraging people to take control of their own health.],
  [“Both my parents passed from various cancers and being a father, and loving being a father, I want to make sure that I spend as much time with him as possible and stick around here for as long as I can, and taking this early detection blood test for cancer was something that allowed me to just have peace of mind, knowing that I was kind of in the driver’s seat,” said Diggs.],
  [The actor recently paired with Cancerguard , a blood test for people ages 50 or older that helps detect more than 50 types and subtypes of cancer before symptoms appear.],
  [“It’s not a diagnosis, but it just lets you know if you should go and take a few more steps further just to see what other specific tests you should take,” noted Diggs.],
  [Healthline spoke with Diggs about his loss and how it has changed his approach to his own health and fatherhood.],
  [This interview has been edited and condensed for clarity and length.],
  [Diggs values life, health more than ever],
  [Diggs explained that his experience with his parents’ cancer was a wake-up call. He lost his mother to breast cancer and his stepfather to colon cancer .],
  [“It almost forces you to look at things differently. [It] makes me value life and health way more than I did before,” he said.],
  [He went on to say that he has been lucky with his health, and that made him feel invincible. Now he has seen that “bad” things can happen, and that opened his eyes. Diggs said that his son helps push him to go to the doctor and take care of his health.],
  [“It gives you kind of a new perspective on life and health and sticking around. When you have people that you care about, you want to be around for them,” he said.],
  [“So for me, after that, it’s become easy to do things like take early detective blood tests for cancer. It’s all of that, watching my [diet], exercising, all that stuff. Living is a luxury. And if, and if we can do everything we can, we should.”],
  [Losing his parents changed his approach to fatherhood],
  [Diggs told Healthline about his 17-year-old son, Walker, and how the experience of losing his parents affected his approach to fatherhood.],
  [“I can’t help but just be aware. I realize now life doesn’t last forever. I realized the importance of parenting. I realized the importance of a solid, healthy, and honest relationship,” Diggs said.],
  [“When I did lose my mother, that was a really tough blow. And when you’re in the midst of something like that, you don’t want to see any positives. I mean, I wouldn’t say I would want it to happen again, but I’m definitely a different person, and I’m definitely a better father, and I’m just more aware of who I am and what my relationships are.”],
  [Why early cancer detection matters],
  [According to a recent report by the American Cancer Society (ACS) , early detection through screenings has significantly improved the survival rates for many cancers, including:],
  [breast],
  [cervical],
  [colorectal],
  [prostate],
  [lung],
  [“We have better screening and better understanding of cancer prevention,” Anton Bilchik , MD, PhD, surgical oncologist, chief of medicine, and director of the Gastrointestinal and Hepatobiliary Program at Providence Saint John’s Cancer Institute in Santa Monica, CA, told Healthline in an earlier interview .],
  [Research has shown that when cancer is detected early, treatment is more effective and survival rates improve dramatically.],
  [“Mortality has everything to do with when you find the cancer in its growth trajectory,” Arif Kamal , MD, chief patient officer for the American Cancer Society, told Healthline in an earlier interview .],
  [The ACS points out that this is why getting regular cancer screenings is so important.],
),
  edited-for-length: false,
)

#pull-quote([Now he has seen that “bad” things can happen, and that opened his eyes.], [Healthline])


{
  #section-label([Features])
  #standard-article(
  title: [GLP-1 Drugs Like Ozempic, Wegovy May Help Treat Anxiety, Depression],
  author: [Healthline],
  source-name: [Healthline],
  images: (),
  paragraphs: (
  [New research suggests that GLP-1s could offer dual benefits for treating both metabolic and mental health issues. Catherine Falls Commercial/Getty Images],
  [A new study found that people taking GLP-1 drugs like Ozempic and Wegovy had a lower risk of worsening depression and anxiety.],
  [The participants also had fewer hospitalizations and required less sick leave from their jobs.],
  [Experts say the drugs’ effects on dopamine signaling and brain inflammation could account for the benefits.],
  [It’s too soon to recommend GLP-1s as a primary treatment for mental health disorders. Further clinical trials are still needed.],
  [Researchers say people living with diabetes often face a higher risk of developing mental health conditions.],
  [Now, a large national study from Sweden found that certain medications commonly prescribed for diabetes and weight loss — specifically GLP-1 receptor agonists like Ozempic and Wegovy — may also help reduce the risk of worsening mental illness in people with anxiety or depression .],
  [The findings, published in the April issue of The Lancet Psychiatry , offer hope for dual benefits in treating both metabolic and mental health issues . While promising, the researchers caution that further clinical trials are needed.],
  [Effects of GLP-1 drugs on mental health disorders],
  [The study analyzed health data from 95,490 people in Sweden who were diagnosed with depression, anxiety, or both, and were also prescribed diabetes medications between 2009 and 2022.],
  [The researchers focused on a class of drugs called GLP-1 receptor agonists . These medications help control blood sugar and reduce appetite by mimicking the body’s natural GLP-1 hormone.],
  [Four specific GLP-1 medications were examined: semaglutide ( Wegovy , Ozempic , Rybelsus), liraglutide (Saxenda), exenatide (Byetta, Bydureon BCise), and dulaglutide ( Trulicity ).],
  [The study compared periods when individuals were taking these medications to periods when they were not, using a “within-individual” design. This approach means each person acted as their own control, reducing the influence of factors like age, gender, or overall health that do not change over time.],
  [Data were gathered from national electronic health registers, including hospital admissions, sick leave records, and death registries, allowing researchers to track worsening mental health events.],
  [The primary outcome was a composite measure that included psychiatric hospitalizations, extended sick leave for psychiatric reasons, hospitalization due to self-harm, or death by suicide.],
  [Secondary outcomes examined worsening of depression or anxiety separately, substance use disorders , and self-harm incidents.],
  [The study also compared GLP-1 receptor agonists with other second-line diabetes medications like empagliflozin (Jardiance), dapagliflozin ( Farxiga ), and sitagliptin ( Januvia ) to see how these medications stacked up against each other in terms of mental health effects.],
  [Statistical models adjusted for time-varying factors such as the order and duration of medication use and concurrent treatment with other psychiatric or antidiabetic drugs.],
  [The aim was to isolate the effects of GLP-1 receptor agonists on mental health as much as possible within the observational data.],
  [Ozempic, Wegovy lower risk of worsening mental illness],
  [Over an average follow-up of 5.2 years, about 23.5% of the cohort used GLP-1 receptor agonists, with semaglutide and liraglutide being the most common.],
  [The study revealed that use of semaglutide was associated with a 42% lower risk of worsening mental illness compared to periods when the same individuals were not taking GLP-1 receptor agonists.],
  [Liraglutide also showed a beneficial effect, though less pronounced, with an 18% reduced risk. In contrast, exenatide and dulaglutide did not show significant associations with mental health outcomes.],
  [When looking at specific mental health conditions, semaglutide use was linked to significantly lower risks of worsening depression, anxiety, and substance use disorders. Liraglutide was associated primarily with reduced risk of worsening depression. Additionally, GLP-1 receptor agonists as a group were associated with a lower risk of self-harm.],
  [Compared directly with other second-line antidiabetic medications, semaglutide was again associated with better mental health outcomes, suggesting its benefits extend beyond glucose control alone. The study also found that these associations held true even when accounting for factors such as sex and the type of mental health diagnosis at study entry.],
  [Additionally, the reduced risk of worsening mental illness was reflected not only in fewer psychiatric hospitalizations but also in reduced sick leave due to mental health reasons, which has implications for work capacity and quality of life.],
  [The researchers took care to rule out potential biases, such as effects due to the sequence of medication use or carryover effects between treatment periods. Their analyses remained consistent when excluding initial days after starting or stopping medication and when focusing on medication use after official approval dates.],
  [GLP-1s may offer dual benefits for metabolic, mental health],
  [Lauren Grawert, MD, clinical advisor at The Garden New Jersey , said it’s believed that GLP-1 medications can provide psychiatric benefits because they can cross the blood-brain barrier and bind to brain regions associated with the reward system. Grawert wasn’t involved in the study.],
  [“These medications may affect the way the brain responds to dopamine signals in these areas, decreasing the overactive reward response that drives impulsivity and cravings for substances,” she told Healthline.],
  [Still, GLP-1s may also exert anti-inflammatory effects on the central nervous system, reducing brain inflammation , which has been linked with depression and anxiety, Grawert said.],
  [“As a result, semaglutide may help stabilize mood and improve emotional regulation by addressing these underlying biological processes in addition to its effects on metabolism,” she explained.],
  [Looking at the implications for treating patients, Jason Kirby, Chief Medical Officer at Recovery Centers of America , said that GLP-1 medications could help people with metabolic and psychiatric disorders, possibly reducing hospitalizations and functional impairment associated with conditions like depression and anxiety. Kirby wasn’t involved in the study.],
  [“However, this was an observational study, so it does not establish causality, and GLP-1 agents should not yet be considered primary treatments for depression or anxiety,” he told Healthline.],
  [According to Kirby, these findings reinforce the importance of integrated care. He said the research represents “a promising avenue for future research at the intersection of psychiatry, addiction medicine, and metabolic health.”],
),
  insert-map: (:),
  word-count: 1000,
  edited-for-length: false,
  debug-mode: false,
)

  #pull-quote([Ozempic, Wegovy lower risk of worsening mental illness  Over an average follow-up of 5.], [Healthline])

}

{
  #standard-article(
  title: [GLP-1s Combined With Healthy Habits May Improve Heart Health in Diabetes],
  author: [Healthline],
  source-name: [Healthline],
  images: (),
  paragraphs: (
  [Combining GLP-1 drugs with a healthy lifestyle may reduce cardiovascular risks in people with diabetes. Image Credit: Witthaya Prasongsin/Getty Images],
  [A recent study found that people with type 2 diabetes who used GLP-1 receptor agonists (GLP-1 RAs) in combination with healthy lifestyle habits had a reduced risk of major adverse cardiovascular events.],
  [The findings show that GLP-1 RAs, when combined with healthy habits, independently improved heart health, though to varying degrees.],
  [The researchers noted that lifestyle interventions remain pivotal in diabetes management and can amplify the benefits of GLP-1 RAs.],
  [Type 2 diabetes is a growing health concern in the United States, overlapping with the obesity epidemic.],
  [According to the Centers for Disease Control and Prevention (CDC) , 40.1 million people in the United States have diabetes, either diagnosed or undiagnosed. That is an estimated 12% of the population.],
  [According to research from 2017 , the prevalence of diabetes will increase by 54% by 2030. This is an estimated 54.9 million people.],
  [Type 2 diabetes can lead to various complications, including cardiovascular disease . This is the leading cause of death among people with diabetes.],
  [A recent study published in The Lancet Diabetes & Endocrinology found that a combination of GLP-1 receptor agonists (GLP-1 RAs) and healthy lifestyle habits can reduce the risk of major adverse cardiovascular events (MACE) in people with type 2 diabetes.],
  [“Our findings underscore that, even in the era of highly effective GLP-1 pharmacotherapy, lifestyle habits remain central to diabetes management and cardiovascular risk reduction and can substantially amplify the benefits of modern medications,” Frank Hu , MD, Fredrick J. Stare Professor of Nutrition and Epidemiology and chair of the Department of Nutrition at the Harvard T. H. Chan School of Public Health, and corresponding author of the study, said in a press release .],
  [GLP-1s and 6 healthy habits lower cardiovasculr risk by 43%],
  [The study used data from the Veterans Affairs’ Million Veteran Program from 2011 to 2023.],
  [The researchers looked at the lifestyle habits, GLP-1 RA usage, and cardiovascular outcomes of over 98,000 adults who had type 2 diabetes and no previous history of cardiovascular disease.],
  [The researchers considered 8 healthy habits:],
  [healthy diet],
  [regular exercise],
  [not smoking],
  [restful sleep],
  [minimal alcohol consumption],
  [good stress management],
  [social connection and support],
  [not having opioid use disorder],
  [The MACEs they considered were:],
  [non-fatal stroke],
  [myocardial infarction (heart attack)],
  [cardiovascular death],
  [The study found that using a GLP-1 RA and maintaining a healthy lifestyle significantly reduced the risk for MACE.],
  [“We know that GLP-1 receptor agonists can improve cardiovascular health in patients with diabetes. We also know that good lifestyle habits such as eating [a] heart-healthy diet, getting regular physical activity, and getting enough quality sleep, are all beneficial in controlling the risk factors that lead to heart disease,” Cheng-Han Chen , MD, board certified interventional cardiologist and medical director of the Structural Heart Program at MemorialCare Saddleback Medical Center in Laguna Hills, CA, who was not involved in the study, told Healthline.],
  [“It is thus not surprising that combining both GLP-1 receptor agonists and healthy lifestyle modifications can have additive beneficial effects.”],
  [Individuals who used a GLP-1 RA and adhered to between six and eight healthy habits showed a 43% lower risk of MACE than those who did not use a GLP-1 RA and adhered to three or fewer habits.],
  [Those who adhered to all eight healthy habits had a 60% reduced risk compared to those who adhered to only one or fewer. Finally, people who used a GLP-1 RA had a 16% lower MACE risk than those who didn’t.],
  [“From a public health perspective, the results underscore the continued importance of population-level investments and policy in promoting healthy diet, physical activity, sleep, stress management, and social connection, even in a modern drug era,” Hu said in the press release.],
  [“As novel therapies expand, scalable lifestyle interventions remain essential for reducing the overall burden of cardiovascular disease and other chronic diseases.”],
  [More studies needed to understand heart health benefits],
  [The researchers noted that the study had limitations.],
  [First, the results were based on observational data. This means that it was possible there was some residual confounding by socioeconomic status and other factors. However, these variables were accounted for during analysis.],
  [Additionally, the study population consisted predominantly of white male veterans.],
  [This may have limited the generalizability of the results. However, the findings were consistent across racial and ethnic groups and between males and females.],
  [“Keeping diabetes under control is a long-term process,” Chen said.],
  [“It is important to understand the composition of your food so that you can make the correct choices. We recommended getting regular physical activity. It is also important to avoid alcohol and tobacco, and to get enough quality sleep.”],
  [Frequently asked questions],
  [How do GLP-1s help manage diabetes?],
  [Glucagon-like peptide-1 (GLP-1s, or GLP-1 RAs), such as Ozempic , Wegovy, and Mounjaro , help manage type 2 diabetes by mimicking the natural hormone GLP-1. This helps increase insulin secretion, reduce liver glucose production, and slow gastric emptying.],
  [They also help curb appetite, promote weight loss, and lower blood sugar.],
  [How can lifestyle changes affect diabetes?],
  [Healthy lifestyle changes can help delay or prevent the onset of type 2 diabetes. They can also help lower your blood glucose (sugar) levels. This can help manage diabetes, potentially help you avoid medication, and even put your diabetes into remission.],
  [The CDC recommends the following lifestyle habits to help manage type 2 diabetes: manage your stress as much as possible, eat a healthy diet , maintain an active lifestyle , and get plenty of sleep .],
  [What are the risk factors for diabetes?],
  [Risk factors for type 2 diabetes include having overweight or obesity , being 35 years old or older, having a family history of diabetes, having prediabetes , having a history of gestational diabetes , and giving birth to a baby weighing 9 lbs or more.],
),
  insert-map: (:),
  word-count: 983,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Bye-Bye Bites: 14 Ways to Get Rid of Mosquito Bites Overnight],
  author: [Greatist],
  source-name: [Greatist],
  images: (),
  paragraphs: (
  [Wondering how to get rid of mosquito bites overnight? Discover simple home remedies for quick relief. From crushed ice to aloe vera, explore easy solutions to soothe itching and inflammation for a peaceful night’s sleep.],
  [If you’re caught without bug bite cream or ointment, don’t worry — plenty of simple home remedies can provide quick relief. From soothing aloe vera to the calming effects of oatmeal , discover easy solutions to alleviate itching and inflammation so you can sleep peacefully.],
  [crushed ice],
  [heat],
  [aloe vera],
  [baking soda],
  [basil],
  [vinegar],
  [onion],
  [thyme],
  [peppermint oil],
  [lemon balm],
  [witch hazel],
  [arnica],
  [chamomile tea],
  [garlic],
  [Crushed ice],
  [Just as you’d ice an injury, icing a bug bite can help decrease inflammation and temporarily numb the pain.],
  [If icy cold treatments aren’t your vibe, you can apply heat instead to soothe your bump.],
  [Aloe vera],
  [Aloe vera gel does more than soothe sunburns! It can also help ease bug bites and help them heal.],
  [Baking soda],
  [Baking soda can remove the itch. To make a paste , mix 1 tablespoon of it with a splash of water (not too much). Apply it to your bite as you would zit cream. Keep it on for 10 minutes before rinsing it off.],
  [Did you know basil (yes, like the kind in your pasta) has a rich history as a skin infection remedy? It contains antioxidants that may bring down bug bite inflammation.],
  [To whip up your own basil rub, boil a couple cups of water with 1/2 ounce of dried basil leaves . Cool the mixture before applying it to a washcloth and gently massaging it onto the bite for sweet relief.],
  [You already know apple cider vinegar (fermented liquid from apples) is a huge player in the natural remedy world.],
  [Some people use it to clean due to its antimicrobial effects , and others mix it into food or drinks for its possible health benefits (like helping with blood sugar issues ).],
  [Its beauty with bites is that it can help ease burning or stinging while disinfecting your scratchy little bump.],
  [Onion juice (while not delicious) has antifungal and antibacterial properties, which could possibly help ward off infection. Plus, it could make your bite sting less. Just dab a bit of raw onion juice onto your bites. The downside? We’re not sure how well it works … and it’s kinda stinky.],
  [Thyme has been used to help with skin concerns for a long time. You can use it to help decrease irritation by chopping it up and applying the teeny leaves directly to your bite for 10 minutes. You can also boil thyme, soak a cloth in the cooled liquid, and wrap it around your bite.],
  [Peppermint oil],
  [Peppermint oil may work as an anti-itch agent. Mix it with carrier oil (like olive oil ) before applying it to your skin, though!],
  [Lemon balm],
  [Another natural anti-itcher and astringent, lemon balm , may be helpful . You can either apply a lemon balm cream or chop up the leaves and apply them right to the bite.],
  [Witch hazel],
  [Witch hazel is a natural wonder with many uses for skin concerns such as acne and psoriasis . It can tackle inflammation and burning while helping your bug bite heal.],
  [This herb may work, but the science is a little dicey . On its own, arnica is toxic, so any over-the-counter products you find have been carefully diluted for your safety.],
  [Chamomile tea],
  [The yummy tea that calms and soothes at bedtime has many other uses, including potentially calming an irritated bug bite. Steep the tea bag for 20 minutes before squeezing it out and applying it to your bite once it’s cooled.],
  [Blend minced garlic with petroleum jelly or fragrance-free lotion. Place the mixture on your bite for 10 minutes before removing it and applying a cool cloth.],
  [How do you make mosquito bites go away immediately?],
  [Icing the bite for 10 minutes and then placing a mixture of baking soda and water on it for 10 minutes is a strong choice .],
  [What does Vicks VapoRub do to mosquito bites?],
  [Though not tested for this purpose, some people turn to Vicks to soothe mosquito bites. It’s possible that its antibacterial and anti-inflammatory properties could help heal and soothe mosquito bites. But FYI, this product isn’t considered the best defense against mosquito bites.],
  [What does toothpaste do to mosquito bites?],
  [Some toothpastes are cooling, so that sensation may offer temporary relief. Some people use toothpaste on insect bites since many toothpastes contain astringents , which can help shrink tissues.],
  [How do I stop mosquitoes from biting me?],
  [Using repellent to prevent bug bites is a good idea. PSA: DEET and lemon eucalyptus oil are safe ways to repel insects.],
  [Mosquitoes are low-key little monsters that cause the most insect bites worldwide. Most bites aren’t serious, but mosquitoes can potentially carry diseases.],
  [Ointments, creams, or simple home remedies can help stop the pesky itch after bites. But remember that some natural substances can cause allergic reactions. That said, it’s always a good idea to do a patch test first.],
),
  insert-map: (:),
  word-count: 874,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [Ultraprocessed Foods As Addictive As Tobacco, Researchers Say],
  author: [Healthline],
  source-name: [Healthline],
  images: (),
  paragraphs: (
  [New research shows that ultraprocessed foods may be as addictive as cigarettes. Image Credit: Alexander Spatari/Getty Images],
  [A recent review found that ultraprocessed foods (UPFs) may be as addictive as tobacco products.],
  [The researchers found that UPFs are designed to heighten reward and accelerate the delivery of reinforcing ingredients.],
  [The “addictive” quality of these foods means they drive compulsive consumption and disrupt appetite regulation.],
  [The review authors suggest that ultraprocessed foods should be subject to regulations similar to those for tobacco products.],
  [Currently, there is no single universal definition of ultraprocessed foods. Some people define them as foods that contain ingredients you would not find in your kitchen cupboards, such as emulsifiers and additives.],
  [Many professionals use the NOVA classification to define ultraprocessed foods. This talks about foods that contain “formulations of ingredients, mostly of exclusive industrial use, typically created by a series of industrial techniques and processes.”],
  [A recent review published in The Millbank Quarterly suggested that ultraprocessed foods may be as addictive as tobacco products.],
  [“I agree with this study, as ultra-processed foods are specifically engineered to be highly appealing to most individuals,” Mir Ali , MD, bariatric surgeon and medical director of MemorialCare Surgical Weight Loss Center at Orange Coast Medical Center in Fountain Valley, CA, who was not involved in the research, told Healthline.],
  [Research from 2023 estimates that over 73% of the foods in the United States are ultraprocessed.],
  [“Cigarettes and UPFs [ultraprocessed foods] are not simply natural products but highly engineered delivery systems designed specifically to maximize biological and psychological reinforcement and habitual overuse,” noted the new study’s research team from Harvard, Duke, and the University of Michigan.],
  [Are ultraprocessed foods addictive?],
  [The review synthesized findings from addiction, public health history, and nutrition in order to identify sensory and structural features that increase the reinforcing potential of both cigarettes and ultraprocessed foods.],
  [“Not everyone is ‘addicted’ to these foods, but for a meaningful minority, they trigger classic addiction-like patterns: strong cravings, loss of control, and continued use despite negative health effects,” said Michelle Routhenstein , preventive cardiology dietitian at EntirelyNourished, who was not involved in the study.],
  [“These foods are deliberately engineered with refined carbs , added fats, salt, and flavor enhancers to maximize reward and repeat consumption, and the industry uses aggressive marketing tactics, especially targeting children,” she told Healthline.],
  [The researchers focused on five key areas:],
  [delivery speed],
  [hedonic engineering, or designing foods to be irresistibly good],
  [dose optimization],
  [environmental ubiquity],
  [deceptive reformulation, or “health washing”],
  [They found that, like cigarettes, ultraprocessed foods are fine-tuned to deliver the right dose of sugar .],
  [“Refined carbohydrates stimulate dopamine release via the vagus nerve , whereas fats do so through intestinal lipid sensing,” the researchers wrote.],
  [“… UPFs with high levels of refined carbohydrates and added fats are some of the most potently rewarding substances in the modern diet. Notably, this refined carbohydrate-fat combination is almost nonexistent in nature.”],
  [The way these foods rapidly deliver “feel-good” chemicals to the brain makes them potentially addictive, similarly to cigarettes.],
  [The review noted that while cigarettes are engineered to deliver nicotine quickly, ultraprocessed foods are engineered to rapidly digest and absorb, as they typically have little to no fiber. This makes it easier for the body to process fat and sugar more quickly.],
  [The researchers also explain that ultraprocessed foods give intentional flavor bursts that fade quickly and textures that melt in your mouth. This all helps to deliver more dopamine and encourages you to eat more.],
  [‘Health washing’ in cigarettes, ultraprocessed foods],
  [According to the review, both the tobacco and food industries have long used a strategy called “health washing.”],
  [This is where products are marketed and reformulated to create an illusion of reduced harm while preserving the core of their addictive properties.],
  [Health washing in the tobacco industry gained traction in the 1950s with the introduction of filters on cigarettes.],
  [These were marketed as protective innovations that would trap tar and particles before they reached the lungs. In reality, filters offer little meaningful benefit.],
  [However, people typically adapted by inhaling deeper or smoking more frequently, which offset any reduction in toxin exposure.],
  [The food industry has taken a similar approach. It uses labels like “low fat” or “sugar-free” to market ultraprocessed foods.],
  [However, these foods still contain the same highly reinforcing ingredient combinations. The issue is that these reformulations offer a superficial appearance of health while the product’s addictive structure and metabolic harms remain intact.],
  [Should ultraprocessed foods be regulated?],
  [The researchers noted at the end of their paper that food and tobacco are not the same thing.],
  [Still, they cautioned that certain ultraprocessed foods function like highly optimized consumables rather than actual food. They recommended that public health policy should reflect this reality.],
  [“Tobacco provides a warning, and tobacco control provides a source of hope,” the researchers wrote.],
  [Due to regulations, smoking rates in the United States have fallen and have “reshaped cultural views of tobacco and eroded trust in the industry.”],
  [“I believe increased education regarding the negative impact of ultra-processed foods is essential to reduce general consumption and improve public health. The strategies used to reduce cigarette consumption have been effective and may be a helpful model for ultra-processed foods as well,” said Ali.],
  [“I don’t think UPFs [ultraprocessed foods] should be regulated exactly like cigarettes, but they do warrant stronger, tobacco-inspired policies: marketing restrictions, clear front-of-package labeling, tighter standards on health claims, and limits in schools or hospitals,” added Routhenstein.],
  [The researchers reminded people that minimally processed and unprocessed foods have sustained human health for millennia.],
  [“Legal action against health damages and misleading health claims, restrictions on UPF advertising, taxation of nutrient-poor UPFs, markedly reducing UPFs in schools and hospitals, and clearer labeling of ultraprocessing could all serve as next steps,” they noted.],
  [“Policies that confront UPFs with the same seriousness that once applied to tobacco, while actively promoting real food, offer the most promising path out of the current crisis.”],
  [Routhenstein agreed and told Healthline that public policy should expand access to fresh, minimally processed foods. This is especially true in lower-income neighborhoods, she explained. Access could be expanded through subsidies, support for local markets and grocery stores, and school or workplace programs.],
  [“Making real food affordable and convenient reduces reliance on UPFs and addresses structural barriers that drive unhealthy eating patterns,” Routhenstein said.],
  [Frequently asked questions],
  [What is the ultraprocessed foods spectrum?],
  [The research review noted that not all processed foods are equal. There is a difference between minimally processed foods and ultraprocessed foods.],
  [Minimally processed foods have only been slightly altered in order for them to be more easily stored, prepared, and eaten. Examples include grinding, pasteurization, fermentation, and freezing.  This allows those foods to be preserved for a longer time and remain safe to eat.],
  [According to the researchers, minimally processed foods may carry a lower risk than ultraprocessed foods.],
  [How can you spot ultraprocessed foods?],
  [The ingredient list is typically the clearest place to see how processed a product really is. The more unfamiliar the ingredients sound, the more likely it is that the product is ultraprocessed.],
  [Signs that food may be ultraprocessed include emulsifiers such as soy lecithin or mono – and diglycerides, long ingredient lists, usually with more than 5 to 7 items, ingredients you wouldn’t cook at home, artificial flavors or colors, isolated starches or protein isolates, and multiple forms of added sugar .],
  [What are alternatives to ultraprocessed foods?],
  [Routhenstein recommended treating ultraprocessed foods as optional rather than everyday staples, especially sugary drinks, packaged sweets, chips, fast food, and heavily processed frozen meals.],
  [“Shift your environment so minimally processed foods are the convenient default, and build meals around fiber-rich carbs, quality protein, and healthy fats to improve satiety and blunt cravings,” she added.],
  [She noted that simple swaps such as sparkling water for soda, fruit and nuts for candy, oats or plain yogurt for sweetened cereals, and batch-cooked meals for frozen entrees can meaningfully lower ultraprocessed food exposure while keeping eating practical and enjoyable.],
),
  insert-map: (:),
  word-count: 1334,
  edited-for-length: false,
  debug-mode: false,
)

}

{
  #standard-article(
  title: [‘Grey’s Anatomy’ and ‘Euphoria’ Star Eric Dane Dies at 53 After ALS Diagnosis],
  author: [Healthline],
  source-name: [Healthline],
  images: (),
  paragraphs: (
  [US actor Eric Dane attends Prime Video’s “Countdown” premiere at the Harmony Gold theatre in Los Angeles on June 18, 2025. Image credit: VALERIE MACON/Getty Images],
  [Actor Eric Dane has died from amyotrophic lateral sclerosis (ALS) at the age of 53.],
  [He had first announced his ALS diagnosis only 10 months prior.],
  [The actor became a strong advocate for research following his diagnosis.],
  [The disease is not curable, but there are treatments that can slow its progression.],
  [There are also treatments that can improve function and comfort for patients.],
  [Actor Eric Dane died on Thursday, February 19, 2026, after a “courageous battle” with amyotrophic lateral sclerosis (ALS) , according to an announcement on his official Instagram account.],
  [“He spent his final days surrounded by dear friends, his devoted wife, Rebecca, and his two beautiful daughters, Billie and Georgia, who were the center of his world,” the post read.],
  [It additionally spoke of his advocacy for awareness and research.],
  [Although not mentioned in the post, Dane had partnered with I AM ALS and its  Push for Progress  initiative, which aims to raise money to accelerate research and expand access to promising new treatments.],
  [Dane also lobbied for the extension of the Accelerating Access to Critical Therapies for ALS Act. This law, which was passed in 2021, provided five years of funding for research and allowed early access to ALS treatments. It is set to expire in 2026, according to reporting from CNN .],
  [The 53-year-old star, best-known for his roles as Dr. Mark “McSteamy” Sloan on “Grey’s Anatomy” and Cal Jacobs in “Euphoria,” first revealed his diagnosis 10 months prior to his death.],
  [In an interview with People at the time, Dane said, “I feel fortunate that I am able to continue working and am looking forward to returning to the set of  Euphoria  next week.”],
  [However, it appears that he did not have as much time left as he had hoped. “[H]is illness progressed far more quickly than anyone could have imagined,” the announcement said.],
  [What is amyotrophic lateral sclerosis (ALS)?],
  [Rab Nawaz Khan , MD, a board certified neurologist who is a consultant at MyMSTeam , told Healthline that ALS is a progressive disease that damages motor neurons, the nerve cells that control voluntary movement.],
  [You might also hear it referred to as “Lou Gehrig’s disease,” due to it becoming widely known after it was diagnosed in baseball player Lou Gehrig.],
  [“The earliest symptoms are often focal weakness, like hand clumsiness, foot drop, tripping, trouble with buttons, or a change in speech clarity,” said Khan. “Many people also notice muscle cramps, twitching, and muscle thinning in the affected area.”],
  [As the disease progresses, weakness can spread to other regions, he noted, affecting walking, arm function, speech, and swallowing.],
  [Eventually, the person’s breathing muscles weaken, leading to symptoms such as poor sleep, morning headaches , and shortness of breath with activity.],
  [“Sensation is usually preserved,” Khan added, “so numbness and tingling are not typical ALS features, and a subset of patients can have changes in thinking or behavior.”],
  [The National Institute of Neurological Disorders and Stroke (NINDS) adds that ALS can happen at any age, although it’s more common between the ages of 55 and 75. Younger men are more likely than younger women to develop ALS, although women catch up as they grow older.],
  [Non-Hispanic white people are most likely to develop the disease. The agency additionally notes a poorly understood link between military service and ALS.],
  [Around 10% of all ALS cases are due to a genetic mutation, according to NINDS.],
  [How is ALS treated?],
  [Khan said that ALS is not yet curable, although there are treatments that can moderately slow its progression. There are also interventions that improve comfort and function.],
  [“Disease-targeted medications include riluzole and edaravone , which can slow decline in certain patients, and a gene-targeted therapy is available for a specific inherited form related to SOD1,” he explained.],
  [However, Khan said the biggest impact often comes from multidisciplinary ALS care, where breathing, nutrition, mobility, and communication are addressed early and proactively.],
  [“Noninvasive ventilation can improve sleep , energy, and quality of life when breathing muscles weaken, and cough assist devices help clear secretions,” he said.],
  [“Nutrition support, speech therapy , communication devices, physical and occupational therapy, and symptom-directed medications for spasticity, drooling, cramps, mood or pseudobulbar affect can meaningfully reduce day-to-day burden,” added Khan.],
  [Research is ongoing, however, and thanks to Dane’s efforts, it is gaining more attention than ever.],
  [Though ALS ultimately claimed his life, his work may help accelerate progress for those still living with the disease.],
),
  insert-map: (:),
  word-count: 766,
  edited-for-length: false,
  debug-mode: false,
)

}

#article-row((
  [
    standard-article(
  title: [We The People: Free Speech],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [The First Amendment. Book bans, disinformation, the wild world of the internet. Free speech debates are all around us. What were the Founding Fathers thinking when they created the First Amendment, and how have the words they wrote in the 18th century been stretched and shaped to fit a world they never could have imagined? It's a story that travels through world wars and culture wars. Through the highest courts and the Ku Klux Klan. Today on Throughline's We the People : What exactly is free speech, and how has the answer to that question changed in the history of the U. S.? (Originally ran as The Freedom of Speech )],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 150,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [Winter Book Club: The Story of Us?],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [What if the real story of human history is a story itself? To kick off our winter book club, we talk with bestselling author Tamim Ansary about his book, "The Invention of Yesterday: A 50,000-Year History Of Human Culture, Conflict And Connection," about why the future of our species might depend on our ability to arrive at a story we all share. This episode originally ran in 2022.],
  [To access bonus episodes and listen to Throughline sponsor-free, subscribe to Throughline+ via Apple Podcasts or at plus.npr.org/throughline .],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 127,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    brief-group((
      brief-item([Throughline (NPR)], source-name: [Throughline (NPR)], [In the mid-1980s, an OBGYN in Brazil noticed that far fewer pregnant women at his hospital were dying from abortion complications. It wasn't a coincidence. Brazilian women had made a discovery that allowed them to safely have abortions at home, despite the country's abortion restrictions. That discovery eventually spread across the globe. 

To manage podcast ad preferences, review the links below:

See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.

Learn more about sponsor message choices: podcastchoices.com/adchoices 

 NPR Privacy Policy])

      brief-item([Throughline (NPR)], source-name: [Throughline (NPR)], [Who owns stolen art? Today on the show, the bloody journey of a Benin Bronze from West Africa to the halls of one of England's most elite universities — a tale of imperialism, betrayal, and the making of the modern world.

To manage podcast ad preferences, review the links below:

See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.

Learn more about sponsor message choices: podcastchoices.com/adchoices 

 NPR Privacy Policy])

    ))
  ],
), ruled-indices: (1, 2,))

#article-row((
  [
    standard-article(
  title: [Why is Cuba in crisis?],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [Cuba is on the brink of collapse – a scenario that 13 U. S. presidents have tried to engineer with no success. Today on the show, the making of the Cuban crisis and what might come next.],
  [Guests: 
 Eloy Viera , lawyer and journalist for El Toque],
  [Lillian Guerra , Cuban-American history professor at the University of Florida],
  [Maria De Los Angeles Torres , professor of Latin American and Latino Studies at the University of Illinois in Chicago],
  [To access bonus episodes and listen to Throughline sponsor-free, subscribe to Throughline+ via Apple Podcasts or at plus.npr.org/throughline .],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 136,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [We The People: Canary in the Coal Mine],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [The Third Amendment.],
  [Maybe you've heard it as part of a punchline. It's the one about quartering troops — two words you probably haven't heard side by side since about the late 1700s.],
  [At first glance, it might not seem super relevant to modern life. But in fact, the U. S. government has gotten away with violating the Third Amendment several times since its ratification — and every time it's gone largely unnoticed.],
  [In a time of escalating political violence, police forces armed with military equipment, and more frequent and devastating natural disasters, why the Third Amendment deserves a closer look. This episode originally ran in 2024.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 146,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#article-row((
  [
    standard-article(
  title: [Embedded: The Black Gate],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [In the Xinjiang region of western China, the government has rounded up and detained hundreds of thousands of Uyghurs and other Muslim ethnic groups. Many haven't been heard from in years, and more still are desperately searching for their families. Western governments have called this crackdown a cultural genocide and a possible crime against humanity.],
  [In this episode, the first of a three-part series from Embedded, NPR correspondent Emily Feng tells the story of one of those people. For years, a Uyghur man named Abdullatif Kucar had no idea what has happened to his wife and young children after they were detained by Chinese authorities. Emilly follows Kucar as he desperately searches for his family.],
  [But this story is bigger than one family. In this series, Emily also travels across Asia and dives into decades of history to uncover the massive Chinese surveillance of Uyghurs, getting exclusive interviews with the people suffering from that surveillance and the people upholding it – who sometimes are one and the same.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 208,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [History of the Self: Smell and Memory],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  ["History" can seem big and imposing. But it's always intensely personal – it's all of our individual experiences that add up to historical events. Over the next few episodes, we're exploring the personal and how it's changed history: from the story of romantic love, to the man who tried to cure aging, to the contents of our dreams...],
  [First up, memory and our sense of smell. What if we told you that the key to time travel has been right in front of our eyes this whole time? Well, it has: it's in our noses. Today on the show, the science — and politics — of smell, and how it links our past and our present. (Originally ran as The Scent of History)],
  [To access bonus episodes and listen to Throughline sponsor-free, subscribe to Throughline+ via Apple Podcasts or at plus.npr.org/throughline.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 181,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#article-row((
  [
    standard-article(
  title: [Love, Throughline],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [We asked you to call us with your stories of looking for love in the 21st century — and man, did you come through. We heard the whole range of human experience in your stories, but one theme rang out loud and clear: dating, and especially online dating, is a struggle.],
  [The data backs this up. Despite the fact that meeting someone today doesn't require much more than swiping on your phone, people who are looking for long-term relationships are lonelier than ever.],
  [Why is it like this? How did love – this thing that's supposed to be beautiful, magical, transformative – turn into a neverending slog? We went searching for answers, and we found them in surprising places. On today's show: a time-hopping, philosophical journey into the origins of modern love.],
  [Correction: An earlier version of this episode incorrectly said that the Jena Romantics shared a house for 10 years. In fact they lived and worked in close proximity, occasionally cohabitating, for approximately five years],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 206,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [Throughline Sleeps],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [Life can be tough. Every day brings new challenges. And in order to get through the waking hours we need rest. Good quality sleep. In this bonus episode, a companion to our episode " The Way We Dream ," we offer you a 30-minute audio journey into the deep. A smooth trip into the place where our minds are free from the confines of our self awareness, our dreams. This episode originally published in January 2022.
 
 To access bonus episodes and listen to Throughline sponsor-free, subscribe to Throughline+ via Apple Podcasts or at plus.npr.org/throughline .],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 135,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#article-row((
  [
    standard-article(
  title: [We The People: Canary in the Coal Mine],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [The Third Amendment. Maybe you've heard it as part of a punchline. It's the one about quartering troops — two words you probably haven't heard side by side since about the late 1700s.],
  [At first glance, it might not seem super relevant to modern life. But in fact, the U. S. government has gotten away with violating the Third Amendment several times since its ratification — and every time it's gone largely unnoticed.],
  [Today on Throughline's We the People : In a time of escalating political violence, police forces armed with military equipment, and more frequent and devastating natural disasters, why the Third Amendment deserves a closer look.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 147,
  edited-for-length: false,
  debug-mode: false,
)

  ],
  [
    standard-article(
  title: [The Aftermath of Collapse: Bronze Age Edition (2021)],
  author: [Throughline (NPR)],
  source-name: [Throughline (NPR)],
  images: (),
  paragraphs: (
  [What happens after everything falls apart? The end of the Bronze Age was a moment when an entire network of ancient civilizations collapsed, leaving behind only clues to what happened. Today, scholars have pieced together a story where everything from climate change to mass migration to natural disasters played a role. What the end of the Bronze Age can teach us about avoiding catastrophe and what comes after collapse.],
  [To manage podcast ad preferences, review the links below:],
  [See pcm.adswizz.com for information about our collection and use of personal data for sponsorship and to manage your podcast sponsorship preferences.],
  [Learn more about sponsor message choices: podcastchoices.com/adchoices],
  [NPR Privacy Policy],
),
  insert-map: (:),
  word-count: 109,
  edited-for-length: false,
  debug-mode: false,
)

  ],
), ruled-indices: (1,))

#colophon([Informed Register], [Vol. 1, No. 019], [2026-03-30])
